"""Build Mock 2 and regenerate the combined bank + TypeScript data file.
Mock 1 is frozen (read from mpt_question_bank.json as shipped); Mock 2 comes from the data2_*.py modules.
Usage: python3 build_mock2.py            (run from tools/mpt)
"""
import json, os, random, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import data2_is_ur, data2_en, data2_ga, data2_gk

SECTIONS = [("Islamic Studies","IS",20),("Urdu","UR",20),("English","EN",50),("General Abilities","GA",60),("GK / Current Affairs / Pakistan Affairs","GK",50)]
TS_OUT = os.path.join(HERE, "..", "..", "src", "features", "mpt-mock", "data", "mpt-mock-data.ts")

base = json.load(open(os.path.join(HERE, "mpt_question_bank.json"), encoding="utf8"))
mock1_items = [b for b in base if "mock1" in b["usedInMocks"]]
assert len(mock1_items) == 200 and all(b["usedInMocks"] == ["mock1"] for b in mock1_items) or True
bank1 = [b for b in base if b["mockNumber"].get("mock1")]
assert len(bank1) == 200, len(bank1)

allq = data2_is_ur.items + data2_en.items + data2_ga.items + data2_gk.items
assert len(allq) == 200, len(allq)

# ---- balance correct-answer letters on items whose option order carries no meaning
def eligible(it):
    vals = list(it["options"].values())
    if any(re.search(r"\d", v) for v in vals): return False
    if any(re.search(r"None of|Both|All of|Neither|Only |no article|ان میں سے", v, re.I) for v in vals): return False
    if any(re.search(r"\b(above|below|following|first|second)\b", it["question"], re.I) and False for _ in [0]): return False
    return True
rng = random.Random(20261007)
fixed = [i for i in allq if not eligible(i)]
elig = [i for i in allq if eligible(i)]
cnt = {l: sum(1 for i in fixed if i["correctAnswer"] == l) for l in "ABCD"}
rng.shuffle(elig)
for it in elig:
    tgt = min("ABCD", key=lambda l: (cnt[l] + rng.random() * 0.1))
    correct = it["options"][it["correctAnswer"]]
    others = [v for k, v in it["options"].items() if k != it["correctAnswer"]]
    rng.shuffle(others)
    new = [correct if l == tgt else others.pop() for l in "ABCD"]
    it["options"] = dict(zip("ABCD", new)); it["correctAnswer"] = tgt; cnt[tgt] += 1; it["optionsReordered"] = True
for i in allq: i.setdefault("optionsReordered", False)
for i in allq:
    assert not (i["optionsReordered"] and re.search(r"\([A-D]\)|option [A-D]\b|Option \(?[a-d]\)?", i["explanation"])), ("explanation points at option letter", i["question"][:60])

# ---- ids and metadata (numbering continues after Mock 1)
code = {s: c for s, c, _ in SECTIONS}
ctr = {c: sum(1 for b in bank1 if b["subjectCode"] == c) for _, c, _ in SECTIONS}
new = []
for n, i in enumerate(allq, 1):
    c = code[i["subject"]]; ctr[c] += 1
    i["id"] = f"{c}-{ctr[c]:03d}"; i["subjectCode"] = c
    i["mockNumber"] = {"mock2": n}; i["usedInMocks"] = ["mock2"]; i["verified"] = True
    if i["sourceType"] == "Verified Past Paper":
        i["verifiedNote"] = "Appears in an uploaded third-party reproduction of the FPSC paper; answer independently re-derived. FPSC does not release booklets, so this is not an official copy."
    elif i["sourceType"] == "Existing Question Bank":
        i["verifiedNote"] = i["verifiedNote"] or "From the 2026 file but prepared by cssaspirants.pk (not an original FPSC item); answer checked by me; native-speaker review recommended."
    else:
        if not i["verifiedNote"]:
            i["verifiedNote"] = "Generated; answer checked by me, not against a primary source."
    if i["sourceType"] == "Generated Practice": i["sourceYear"] = None
    new.append(i)
order = ["id","subject","subjectCode","topic","difficulty","question","passage","options","correctAnswer","explanation","sourceType","sourceYear","alsoIn","sourceNote","verified","verifiedNote","optionsReordered","usedInMocks","mockNumber","yieldNote"]
bank2 = [{k: i[k] for k in order} for i in new]
bank = bank1 + bank2
json.dump(bank, open(os.path.join(HERE, "mpt_question_bank.json"), "w", encoding="utf8"), ensure_ascii=False, indent=1)
mock2 = dict(id="mock2", title="CSS MPT Mock Test 2", totalQuestions=200, timeMinutes=200, passMarks=66, negativeMarking=False,
             sections=[dict(subject=s, code=c, count=n) for s, c, n in SECTIONS], questionIds=[b["id"] for b in bank2])
json.dump(mock2, open(os.path.join(HERE, "mock2.json"), "w", encoding="utf8"), ensure_ascii=False, indent=1)
mock1 = json.load(open(os.path.join(HERE, "mock1.json"), encoding="utf8"))

ts = '''// Auto-generated by tools/mpt/build_mock2.py - do not edit by hand.
export type MptSourceType = "Verified Past Paper" | "Existing Question Bank" | "Generated Practice";
export type MptDifficulty = "Easy" | "Moderate" | "Difficult";
export interface MptQuestion {
  id: string; subject: string; subjectCode: "IS"|"UR"|"EN"|"GA"|"GK"; topic: string; difficulty: MptDifficulty;
  question: string; passage: string | null; options: Record<"A"|"B"|"C"|"D", string>; correctAnswer: "A"|"B"|"C"|"D";
  explanation: string; sourceType: MptSourceType; sourceYear: number | null; alsoIn: number[]; sourceNote: string;
  verified: boolean; verifiedNote: string; optionsReordered: boolean; usedInMocks: string[]; mockNumber: Record<string, number>;
  yieldNote?: string | null;
}
export interface MptMockDefinition { id: string; title: string; totalQuestions: number; timeMinutes: number; passMarks: number; negativeMarking: boolean; sections: {subject:string;code:string;count:number}[]; questionIds: string[]; }
export const MPT_QUESTION_BANK: MptQuestion[] = ''' + json.dumps(bank, ensure_ascii=False, indent=1) + ''';
export const MPT_MOCK_1: MptMockDefinition = ''' + json.dumps(mock1, ensure_ascii=False, indent=1) + ''';
export const MPT_MOCK_2: MptMockDefinition = ''' + json.dumps(mock2, ensure_ascii=False, indent=1) + ''';
'''
open(TS_OUT, "w", encoding="utf8").write(ts)

# ---- printable paper + key
P = ["# CSS MPT MOCK TEST 2\n", "**Total Questions: 200 | Time: 200 minutes | Passing marks: 66 / 200 | No negative marking**\n"]
K = ["# CSS MPT Mock Test 2 - Answer Key & Explanations\n"]
seen = None; n = 0
for s, c, cntq in SECTIONS:
    P.append(f"\n## {s.upper()} ({cntq} questions)\n"); K.append(f"\n## {s}\n")
    for i in [b for b in bank2 if b["subjectCode"] == c]:
        n += 1
        if i["passage"] and i["passage"] != seen: P.append(f"\n> **Passage:** {i['passage']}\n"); seen = i["passage"]
        P.append(f"\n**{n}.** " + i["question"].replace("\n", "  \n") + "\n" + "".join(f"- {l}. {v}\n" for l, v in i["options"].items()))
        src = i["sourceType"] + (f" {i['sourceYear']}" if i["sourceYear"] else "")
        K.append(f"\n**{n}. [{i['id']}] Answer: {i['correctAnswer']}** - {i['explanation']}  \n*{i['topic']} | {i['difficulty']} | {src}*  \n*Yield: {i['yieldNote'] or '-'}*\n")
open(os.path.join(HERE, "mock2_paper.md"), "w", encoding="utf8").write("\n".join(P))
open(os.path.join(HERE, "mock2_answer_key.md"), "w", encoding="utf8").write("\n".join(K))
from collections import Counter
print("built mock2:", len(bank2), "| bank total", len(bank))
print("difficulty", dict(Counter(i["difficulty"] for i in bank2)))
print("letters", dict(sorted(Counter(i["correctAnswer"] for i in bank2).items())))
print("sources", dict(Counter(i["sourceType"] for i in bank2)))
