"""Mock 2 - Islamic Studies (20) and Urdu (20)."""
from helpers2 import *
IS = "Islamic Studies"; UR = "Urdu"
P23 = "Appears in the uploaded 2023 Special reproduction (third-party, not an official FPSC copy); answer re-derived independently."
P25 = "Appears in the uploaded 2025 reproduction (scanned, third-party); answer re-derived independently."
YS = "Seerah/Khulafa/fiqh questions appear in every parsed paper (2022, 2023, 2025, 2026); keyword count: about 37 Seerah and 12 Khulafa items."
YQ = "Surah/Quran-fact questions appear in all four parsed papers (about 21 items by keyword count)."
YF = "Fiqh/Hadith terminology appears in 2022, 2023, 2025 and 2026 (about 17 items by keyword count)."
def I(*a, **k): return q(IS, *a, **k)
def U(*a, **k): return q(UR, *a, **k)

is_items = [
 # ---- from uploaded past papers (8)
 I("Seerah","Easy",VP,2023,[],"The Holy Prophet Muhammad (SAW) belonged to which tribe?",
   ["Quraysh","Khazraj","Makkan tribe of Banu Makki","Banu Umayyah"],"A",
   "The Prophet (SAW) belonged to the Banu Hashim clan of the Quraysh of Makkah. Banu Umayyah was a different clan of Quraysh; 'Makki' only means 'of Makkah'.",YS,P23+" Options tidied (spelling).", ),
 I("Prophets","Difficult",VP,2023,[],"Which Prophet (AS) is known as 'Khateeb-ul-Anbiya' (the orator among the prophets)?",
   ["Hazrat Dawood (AS)","Hazrat Nooh (AS)","Hazrat Yaqoob (AS)","Hazrat Shu'ayb (AS)"],"D",
   "Hazrat Shu'ayb (AS), the prophet sent to Madyan, is traditionally called Khatib al-Anbiya because of his eloquence.",YS,P23),
 I("Khulafa-e-Rashidee","Moderate",VP,2023,[],"Who advised Hazrat Abu Bakr (RA) to compile the Holy Quran in one book?",
   ["Hazrat Umar (RA)","Hazrat Usman (RA)","Hazrat Ali (RA)","Hazrat Zaid bin Thabit (RA)"],"A",
   "After many huffaz were martyred at Yamama (12 AH), Hazrat Umar (RA) urged Abu Bakr (RA) to compile the Quran; Zaid bin Thabit (RA) was then appointed to do the work (Sahih Bukhari). Zaid is the compiler, not the adviser.",YS,P23),
 I("Quran","Easy",VP,2023,[],"Which night does the Holy Quran describe as better than a thousand months?",
   ["Night of Miraj","Night of Eid-ul-Fitr","Laylat-ul-Qadr","Night of Bara'at"],"C",
   "Surah Al-Qadr (97:3): 'The Night of Qadr is better than a thousand months.'",YQ,P23+" Stem corrected from 'nights' to 'months' to match Surah Al-Qadr."),
 I("Seerah","Moderate",VP,2023,[],"On arrival in Madinah, the Prophet (SAW) stayed at the house of Hazrat Abu Ayyub Ansari (RA) for about ______ months.",
   ["7","8","9","12"],"A",
   "He stayed about seven months, until Masjid-e-Nabawi and his rooms were built.",YS,P23),
 I("Islamic Literature","Difficult",VP,2025,[],"Who is the author of the famous book 'Kitab-ul-Kharaj' on land revenue and public finance?",
   ["Imam Malik","Ibn Khaldun","Imam Abu Yusuf","Imam Shafi'i"],"C",
   "Qadi Abu Yusuf (d. 182 AH), chief judge under Harun al-Rashid and a student of Imam Abu Hanifa, wrote Kitab-ul-Kharaj at the caliph's request.",YF,P25),
 I("Seerah","Easy",VP,2025,[],"The Jewish tribe Banu Nadir lived in:",
   ["Makkah","Madinah","Yemen","Ta'if"],"B",
   "Banu Nadir lived on the outskirts of Madinah and were expelled after breaking their agreement with the Prophet (SAW) in 4 AH.",YS,P25),
 I("Fiqh History","Difficult",VP,2023,[],"The Maliki school of fiqh was introduced in Spain (Andalus) in the reign of:",
   ["Hisham I","Abdul Rehman I","Ibn-e-Ishaq","Yazid"],"A",
   "Maliki fiqh became the school of Andalus under the Umayyad amir Hisham I (788-796), who favoured the students of Imam Malik. Before that the school of Imam Awza'i had been followed.",YF,P23+" Source option spelled 'Hashim'; read as Hisham I (answer reasoned from history, not copied from the source key)."),
 # ---- generated (12)
 I("Quran","Easy",GP,None,[],"Which Surah is recited in every rak'at of the daily prayer (salah)?",
   ["Surah Al-Fatiha","Surah Al-Ikhlas","Surah Yaseen","Surah Al-Baqarah"],"A",
   "The Prophet (SAW) said there is no prayer without Surah Al-Fatiha; it is recited in every rak'at.",YQ),
 I("Quran","Moderate",GP,None,[],"Which Surah of the Quran does NOT begin with 'Bismillah-ir-Rahman-ir-Rahim'?",
   ["Surah Al-Anfal","Surah At-Tawbah","Surah Al-Mulk","Surah An-Naml"],"B",
   "Surah At-Tawbah (Bara'at, Surah 9) is the only Surah that does not open with the Bismillah.",YQ),
 I("Quran","Difficult",GP,None,[],"In which Surah does 'Bismillah' occur twice, once at the opening and once inside the text of the Surah?",
   ["Surah Al-Baqarah","Surah An-Naml","Surah Al-Hajj","Surah Saba"],"B",
   "In Surah An-Naml (27:30) the letter of Sulayman (AS) to the Queen of Saba begins with Bismillah, so the phrase occurs twice in this Surah.",YQ),
 I("Seerah","Moderate",GP,None,[],"The Battle of Uhud was fought in which year of Hijrah?",
   ["2 AH","3 AH","4 AH","5 AH"],"B",
   "Uhud was fought in Shawwal 3 AH. Badr was 2 AH, Khandaq 5 AH.",YS),
 I("Seerah","Moderate",GP,None,[],"Who suggested digging a trench around Madinah in the Battle of Khandaq (Ahzab)?",
   ["Hazrat Salman Farsi (RA)","Hazrat Khalid bin Walid (RA)","Hazrat Abu Dharr Ghifari (RA)","Hazrat Bilal (RA)"],"A",
   "Hazrat Salman Farsi (RA) suggested the Persian practice of defending a city with a trench; the Prophet (SAW) and the Companions dug it in 5 AH.",YS),
 I("Khulafa-e-Rashidee","Easy",GP,None,[],"The Hijri calendar was introduced during the caliphate of:",
   ["Hazrat Abu Bakr (RA)","Hazrat Umar (RA)","Hazrat Usman (RA)","Hazrat Ali (RA)"],"B",
   "Hazrat Umar (RA) fixed the Hijrah as the start of the Islamic calendar in about 17 AH, with Muharram as the first month.",YS),
 I("Companions","Difficult",GP,None,[],"Which Companion of the Prophet (SAW) is known as 'Amin-ul-Ummah' (the trustworthy of this Ummah)?",
   ["Hazrat Abu Ubaidah bin al-Jarrah (RA)","Hazrat Sa'd bin Abi Waqqas (RA)","Hazrat Zubair bin al-Awwam (RA)","Hazrat Talha bin Ubaidullah (RA)"],"A",
   "The Prophet (SAW) gave Abu Ubaidah bin al-Jarrah (RA) this title; he was one of the ten promised Paradise and later commanded the Muslim armies in Syria.",YS),
 I("Fiqh","Moderate",GP,None,[],"The nisab (minimum taxable amount) of gold for Zakat is approximately:",
   ["7.5 tola (about 87.5 grams)","5 tola (about 58 grams)","10 tola (about 117 grams)","52.5 tola (about 612 grams)"],"A",
   "Gold nisab is 20 mithqal, about 87.48 g or 7.5 tola. 52.5 tola (about 612 g) is the nisab of silver.",YF),
 I("Khulafa-e-Rashidee","Difficult",GP,None,[],"The first Muslim naval expedition (to Cyprus) took place during the caliphate of:",
   ["Hazrat Abu Bakr (RA)","Hazrat Umar (RA)","Hazrat Usman (RA)","Hazrat Ali (RA)"],"C",
   "Hazrat Umar (RA) had not permitted sea campaigns; under Hazrat Usman (RA) the governor Muawiyah (RA) led the first naval expedition to Cyprus (about 28 AH).",YS),
 I("Quran","Difficult",GP,None,[],"Surah Al-Fath, which opens with 'Verily We have granted you a manifest victory', was revealed in connection with which event?",
   ["The return from the Treaty of Hudaybiyyah","The Conquest of Makkah","The Battle of Badr","The Migration to Abyssinia"],"A",
   "Surah Al-Fath (48) was revealed as the Prophet (SAW) returned from Hudaybiyyah in 6 AH; the 'manifest victory' refers to the treaty (Sahih Bukhari).",YQ),
 I("Hadith","Difficult",GP,None,[],"Which Imam compiled the 'Musnad', a collection of roughly thirty thousand narrations arranged by Companion?",
   ["Imam Abu Hanifa","Imam Shafi'i","Imam Ahmad bin Hanbal","Imam Malik"],"C",
   "Musnad Ahmad, compiled by Imam Ahmad bin Hanbal (d. 241 AH), is among the largest Hadith collections, arranged by the narrating Companion.",YF),
 I("Seerah","Moderate",GP,None,[],"'Aam-ul-Huzn' (the Year of Sorrow) refers to the year in which the Prophet (SAW) lost:",
   ["Hazrat Hamza (RA) and Abu Talib","Hazrat Khadijah (RA) and Abu Talib","Hazrat Abu Bakr (RA) and Hazrat Khadijah (RA)","Hazrat Ibrahim (RA) and Hazrat Fatimah (RA)"],"B",
   "In the 10th year of prophethood the Prophet (SAW) lost his wife Hazrat Khadijah (RA) and his uncle and protector Abu Talib, a few weeks apart.",YS),
]

NR = "Urdu item: checked by me only; please have a native speaker skim it before the exam."
YU = "Urdu sana'i/qawaid/muhavare/daftari Urdu recur in 2025 and 2026 (Urdu pages are images, so counted by reading them, not by keyword search)."
urdu_items = [
 # ---- 2025 paper (7)
 U("ضرب الامثال","Moderate",VP,2025,[],"کون سی ضرب المثل درست ہے؟",
   ["صبحِ بنارس، شامِ اودھ","صبحِ بنارس، شامِ لاہور","صبحِ بنارس، شامِ آگرہ","صبحِ بنارس، شامِ کشمیر"],"A",
   "مشہور ضرب المثل ’’صبحِ بنارس، شامِ اودھ‘‘ ہے، یعنی بنارس کی صبح اور اودھ (لکھنؤ) کی شام اپنی خوبصورتی میں مثالی ہیں۔",YU,P25,verif=NR),
 U("محاورات/مفہوم","Difficult",VP,2025,[],"’’قوتِ لایموت‘‘ کا مفہوم کیا ہے؟",
   ["قوت کا بھرپور اظہار","وہ قوت جو موت کا مقابلہ کر سکے","قوت کا ناپید ہو جانا","اتنی خوراک جس سے زندگی قائم رہے"],"D",
   "’’لایموت‘‘ کا مطلب ہے جس سے آدمی مر نہ جائے؛ قوتِ لایموت سے مراد گزارے بھر یعنی اتنی خوراک ہے جس سے جان بچی رہے۔",YU,P25,verif=NR),
 U("قواعد","Difficult",VP,2025,[],"وہ حروف جو اسم یا فعل کے ساتھ مل کر اس میں خاص زور یا خصوصیت پیدا کریں، کیا کہلاتے ہیں؟",
   ["حروفِ تنبیہ","حروفِ تردید","حروفِ مفاجات","حروفِ تخصیص"],"D",
   "’’ہی، تو، بھی، ہی‘‘ جیسے الفاظ جو کسی لفظ میں خصوصیت یا حصر پیدا کریں، حروفِ تخصیص کہلاتے ہیں۔",YU,P25,verif=NR),
 U("قواعد","Difficult",VP,2025,[],"جن الفاظ یا جملوں کے درمیان حرفِ عطف آئے، ان میں سے پہلے لفظ یا جملے کو کیا کہتے ہیں؟",
   ["معطوف","معطوف علیہ","حرفِ بیان","متعلقِ فعل"],"B",
   "عطف میں پہلا لفظ ’’معطوف علیہ‘‘ اور حرفِ عطف کے بعد آنے والا دوسرا لفظ ’’معطوف‘‘ کہلاتا ہے۔ مثال: علی اور احمد، میں ’’علی‘‘ معطوف علیہ اور ’’احمد‘‘ معطوف ہے۔",YU,P25+" The source's underlined key (معطوف) disagrees with standard grammar; the key here (معطوف علیہ) was re-derived.",verif=NR),
 U("دفتری اردو/ترجمہ","Moderate",VP,2025,[],"’’At one's beck and call‘‘ کا درست ترجمہ کیا ہے؟",
   ["اشارے پر ہونا","آگے پیچھے ہونا","عاشق ہونا","ملازم ہونا"],"A",
   "’’At one's beck and call‘‘ کا مطلب ہے ہر وقت حکم یا اشارے کا منتظر ہونا، یعنی اشارے پر ہونا۔",YU,P25,verif=NR),
 U("دفتری اردو/ترجمہ","Easy",VP,2025,[],"’’Sum and substance‘‘ کا مطلب کیا ہے؟",
   ["حاصل ضرب","خلاصہ","منافع","تنخواہ"],"B",
   "’’Sum and substance‘‘ سے مراد کسی بات کا خلاصہ یا لبِ لباب ہے۔",YU,P25,verif=NR),
 U("ضرب الامثال","Moderate",VP,2025,[],"’’Nearer the church, farther from God‘‘ کا درست اردو ترجمہ (مماثل ضرب المثل) کیا ہے؟",
   ["بغل میں بچہ، شہر میں ڈھنڈورا","چراغ تلے اندھیرا","دور کے ڈھول سہانے","درزی کے کپڑے پھٹے ہوئے"],"B",
   "جو چیز مقدس مقام کے جتنی قریب ہو، اتنی ہی دین سے دور ہو، یہ ’’چراغ تلے اندھیرا‘‘ کا مفہوم ہے۔",YU,P25,verif=NR),
 # ---- 2026 file, prepared by cssaspirants.pk (6)
 U("الفاظ کے معنی","Easy",EQB,2026,[],"’’مشاہرہ‘‘ کا ہم معنی لفظ کون سا ہے؟",
   ["مشہور","تنخواہ","مشاورت","قیمت"],"B","’’مشاہرہ‘‘ کا مطلب ماہانہ تنخواہ ہے۔",YU,"Prepared by cssaspirants.pk for the 2026 file (not an original FPSC item); answer checked by me.",verif=NR),
 U("قواعد","Easy",EQB,2026,[],"’’بکری‘‘ کا مذکر کیا ہے؟",
   ["بکرا","بکریاں","بکر","ان میں سے کوئی نہیں"],"A","’’بکری‘‘ کا مذکر ’’بکرا‘‘ ہے۔",YU,"Prepared by cssaspirants.pk for the 2026 file (not an original FPSC item); answer checked by me.",verif=NR),
 U("ادبیات","Easy",EQB,2026,[],"مرزا غالب کا اصل نام کیا تھا؟",
   ["اسد اللہ خان","نجم الدولہ","مرزا فرحت اللہ","ان میں سے کوئی نہیں"],"A","غالب کا اصل نام مرزا اسد اللہ خان تھا؛ ’’نجم الدولہ‘‘ ان کا خطاب تھا۔",YU,"Prepared by cssaspirants.pk for the 2026 file (not an original FPSC item); answer checked by me.",verif=NR),
 U("دفتری اردو/ترجمہ","Moderate",EQB,2026,[],"’’Office Memorandum‘‘ کو دفتری اردو میں کیا کہتے ہیں؟",
   ["دفتری یادداشت","یاد دہانی کا خط","نیم سرکاری خط","ان میں سے کوئی نہیں"],"A","سرکاری دفاتر میں Office Memorandum کے لیے ’’دفتری یادداشت‘‘ استعمال ہوتا ہے۔",YU,"Prepared by cssaspirants.pk for the 2026 file (not an original FPSC item); answer checked by me.",verif=NR),
 U("دفتری اردو/ترجمہ","Easy",EQB,2026,[],"’’Better late than never‘‘ کا درست ترجمہ کیا ہے؟",
   ["دیر آید درست آید","جلدی کا کام شیطان کا","وقت کسی کا انتظار نہیں کرتا","ان میں سے کوئی نہیں"],"A","’’دیر آید درست آید‘‘ فارسی کہاوت ہے جو اسی مفہوم کے لیے بولی جاتی ہے۔",YU,"Prepared by cssaspirants.pk for the 2026 file (not an original FPSC item); answer checked by me.",verif=NR),
 U("دفتری اردو/ترجمہ","Moderate",EQB,2026,[],"’’File‘‘ کو دفتری اردو میں کیا کہتے ہیں؟",
   ["مصل","مثل","مسل","ان میں سے کوئی نہیں"],"C","دفتری اردو میں کاغذات کے مجموعے (File) کو ’’مسل‘‘ کہتے ہیں۔",YU,"Prepared by cssaspirants.pk for the 2026 file (not an original FPSC item); answer checked by me.",verif=NR),
 # ---- generated (7)
 U("ادبیات","Moderate",GP,None,[],"اردو کا پہلا ناول عام طور پر کسے مانا جاتا ہے؟",
   ["مراۃ العروس","امراؤ جان ادا","فسانۂ آزاد","گودان"],"A",
   "ڈپٹی نذیر احمد کا ناول ’’مراۃ العروس‘‘ (1869) روایتی طور پر اردو کا پہلا ناول کہلاتا ہے (بعض نقاد اس سے اختلاف کرتے ہیں)۔",YU,verif=NR),
 U("صنائع بدائع","Difficult",GP,None,[],"شعر میں ایسے الفاظ لانا جن میں باہم مناسبت ہو مگر تضاد کا تعلق نہ ہو، کون سی صنعت کہلاتی ہے؟",
   ["صنعتِ تضاد","صنعتِ تکرار","صنعتِ مراعات النظیر","صنعتِ ایہام"],"C",
   "ایسے الفاظ کا جمع کرنا جن میں معنوی مناسبت ہو (جیسے چمن، پھول، بلبل) مگر تضاد کی نسبت نہ ہو، ’’مراعات النظیر‘‘ کہلاتا ہے۔",YU,verif=NR),
 U("ادبیات","Moderate",GP,None,[],"’’آبِ حیات‘‘ کے مصنف کون ہیں؟",
   ["الطاف حسین حالی","محمد حسین آزاد","شبلی نعمانی","مولوی عبد الحق"],"B",
   "’’آبِ حیات‘‘ (1880) اردو شعرا کے تذکرے پر مشتمل محمد حسین آزاد کی مشہور کتاب ہے۔",YU,verif=NR),
 U("ادبیات","Difficult",GP,None,[],"علمِ عروض کے بانی کس عالم کو مانا جاتا ہے؟",
   ["خلیل بن احمد فراہیدی","امام ابو حنیفہ","ابنِ سینا","جاحظ"],"A",
   "علمِ عروض کی بنیاد عرب عالم خلیل بن احمد فراہیدی (دوسری صدی ہجری) نے رکھی۔",YU,verif=NR),
 U("محاورات","Easy",GP,None,[],"محاورہ ’’آنکھوں میں دھول جھونکنا‘‘ کا مطلب کیا ہے؟",
   ["دھوکا دینا","آنکھیں بند کرنا","غصہ کرنا","رونا"],"A","’’آنکھوں میں دھول جھونکنا‘‘ کا مطلب ہے کسی کو چالاکی سے دھوکا دینا۔",YU,verif=NR),
 U("اصنافِ سخن","Easy",GP,None,[],"غزل کے پہلے شعر کو، جس کے دونوں مصرعے ہم قافیہ ہوتے ہیں، کیا کہتے ہیں؟",
   ["مقطع","مطلع","ردیف","قافیہ"],"B","غزل کا پہلا شعر مطلع کہلاتا ہے اور آخری شعر، جس میں شاعر کا تخلص ہو، مقطع۔",YU,verif=NR),
 U("ادبیات","Difficult",GP,None,[],"اردو کی ابتدائی مثنوی ’’کدم راؤ پدم راؤ‘‘ کے مصنف کون ہیں؟",
   ["فخر الدین نظامی","ملا وجہی","غواصی","ابن نشاطی"],"A",
   "’’کدم راؤ پدم راؤ‘‘ بہمنی دور کے شاعر فخر الدین نظامی کی مثنوی ہے اور اسے اردو کی ابتدائی مثنویوں میں شمار کیا جاتا ہے۔",YU,verif=NR),
]
assert len(is_items)==20 and len(urdu_items)==20, (len(is_items),len(urdu_items))
items = is_items + urdu_items
