from helpers import *
IS="Islamic Studies"; UR="Urdu"
NV="Third-party reproduction of FPSC paper; answer independently checked."
items=[
q(IS,"Quran","Easy",VP,2025,[2026],"In which Surah are the rules of distribution of Mall-e-Ghaneemat (war booty) mentioned?",["Surah Anfal","Surah Tawbah","Surah Nisa","None of these"],"A","Surah Al-Anfal (8) opens with the question of war spoils and 8:41 lays down their division (one-fifth to Allah, the Messenger and the needy).",NV),
q(IS,"Quran","Moderate",VP,2025,[2026],"In how many Surahs are Huroof-e-Muqatta'at (disjointed letters) found?",["20","25","29","None of these"],"C","Disjointed letters such as Alif-Lam-Mim open 29 Surahs of the Quran.",NV),
q(IS,"Quran","Moderate",VP,2025,[2026],"How many times is the name 'Muhammad' (SAW) mentioned in the Holy Quran?",["4","5","6","None of these"],"A","The name Muhammad occurs four times: 3:144, 33:40, 47:2 and 48:29 (Ahmad appears once, 61:6).",NV),
q(IS,"Hadith","Moderate",VP,2025,[2026],"For which Surah did the Holy Prophet (SAW) say that 'it made me old'?",["Surah Hood","Sura Samood","Sura Aad","None of these"],"A","In the well-known hadith (Tirmidhi) the Prophet said that Surah Hud and its sister Surahs made him grey.",NV),
q(IS,"Islamic Literature","Moderate",VP,2025,[2026],"Who is the author of the book 'Sunnat Khair Ul Anam'?",["Qazi Salman Mansoorpuri","Peer Muhammad Karam Shah","Mufti Muhammad Shafi","None of these"],"B","Sunnat-e-Khair-ul-Anam was written by Pir Muhammad Karam Shah al-Azhari.",NV),
q(IS,"Seerah","Easy",VP,2025,[2026],"Which was the last Ghazwa of the Holy Prophet (SAW)?",["Khyber","Tabook","Hunain","None of these"],"B","Tabuk (9 AH) was the last expedition led personally by the Prophet (SAW).",NV),
q(IS,"Seerah","Moderate",VP,2025,[2026],"What was the real name of the Holy Prophet's (SAW) uncle Abu Talib?",["Abdullah","Abd Munaf","Abd Kaaba","None of these"],"B","Abu Talib's given name was Abd Manaf ibn Abd al-Muttalib; 'Abu Talib' is his kunyah.",NV),
q(IS,"Seerah","Moderate",VP,2025,[2026],"The Ghazwa of Hunain was fought against ______ tribe.",["Aws","Khazraj","Hawazin","Kinana"],"C","Hunain (8 AH), fought soon after the conquest of Makkah, was against the Hawazin (with Thaqif).",NV),
q(IS,"Seerah","Difficult",VP,2025,[2026],"The battlefield of Badr is situated near the city of:",["Makkah","Jeddah","Taif","None of these"],"D","Badr lies about 130 km south-west of Madinah, so none of the listed cities is correct.",NV),
q(IS,"Khulafa-e-Rashideen","Moderate",VP,2025,[2026],"Where was the election of Caliph Abu Bakr (RA) held?",["House of Abu Bakr RA","Masjid-e-Nabvi","Masjid-e-Haram","None of these"],"D","He was chosen at Saqifa Bani Sa'ida, a covered courtyard of the Ansar's clan, not at any of the listed places.",NV),
q(IS,"Khulafa-e-Rashideen","Difficult",VP,2025,[2026],"Which commander appointed by the Holy Prophet (SAW) was not removed by Hazrat Abu Bakr (RA)?",["Usama b. Zaid","Khalid b. Waleed","Tariq b. Ziyad","Maaz b. Jabal"],"A","Abu Bakr sent Usama's army as the Prophet had ordered and kept him in command despite objections from senior Companions.",NV),
q(IS,"Fiqh","Easy",VP,2025,[2026],"In the books of Islamic Jurisprudence, the Law of Inheritance is called:",["Ilm Ul Fiqah","Ilm Ul Arooz","Ilm Ul Faraiz","None of these"],"C","Ilm al-Fara'id is the science of the fixed shares of inheritance (Quran 4:11-12, 176).",NV),
q(IS,"Fiqh","Moderate",VP,2025,[2026],"When someone declares his wife to be like his mahram female relatives (e.g. his mother), that act is called:",["Khula","Eela","Zihar","None of these"],"C","Zihar is comparing one's wife to a mahram woman; it is dealt with in Surah Al-Mujadila (58:2-4) and requires kaffarah.",NV),
q(IS,"Seerah","Moderate",VP,2023,[],"The Treaty of Al-Hudaibiyah was scribed by:",["Hazrat Abu Bakr (RA)","Hazrat Umar (RA)","Hazrat Usman (RA)","Hazrat Ali Al-Murtaza (RA)"],"D","Ali ibn Abi Talib wrote the treaty at the Prophet's dictation (6 AH).",NV),
q(IS,"Islamic History","Moderate",VP,2023,[],"The battle of Yarmuk was fought between the Muslims and:",["Romans","Jews","Persians","None of these"],"A","Yarmuk (636 CE, Caliph Umar's reign) was won against the Byzantine (Roman) army, opening Syria to the Muslims.",NV),
q(IS,"Hadith","Difficult",VP,2023,[],"Who compiled the first work of Hadith 'Sahifa-e-Sadiqa'?",["Hazrat Abu Bakar (RA)","Hazrat Abdullah bin Amr (RA)","Hazrat Abu Hunain (RA)","Imam Bukhari (RA)"],"B","Abdullah ibn Amr ibn al-As wrote down hadith in his Sahifa Sadiqa with the Prophet's permission.",NV),
q(IS,"Seerah","Moderate",VP,2023,[],"In what year did 'Bait-e-Rizwan' take place?",["5 AH","6 AH","7 AH","8 AH"],"B","The pledge under the tree at Hudaibiyah took place in 6 AH (Quran 48:18).",NV),
q(IS,"Pillars of Islam","Moderate",VP,2023,[],"According to the Quran there are ______ heads (categories) where Zakat can be spent.",["6","7","8","None of these"],"C","Surah At-Tawbah 9:60 lists eight categories of Zakat recipients.",NV),
q(IS,"Seerah","Moderate",VP,2022,[],"For how long did the Prophet (SAW) and his companions remain besieged in Shi'ab-e-Abi Talib?",["One year","Two years","Three years","None of these"],"C","The boycott by Quraysh lasted about three years (7th to 10th year of prophethood).",NV),
q(IS,"Quran","Easy",VP,2025,[],"Which Surah of the Quran mentions the event of Miraj (the Ascension)?",["Surah Al-Ahzab","Surah Al-Isra","Surah Al-Baqarah","Surah Al-Mulk"],"B","Surah Al-Isra (17:1) opens with the night journey of the Prophet from Masjid al-Haram to Masjid al-Aqsa.",NV),
]
def U(topic,diff,src,year,also,stem,opts,ans,expl,note=""): return q(UR,topic,diff,src,year,also,stem,opts,ans,expl,note)
N25="Third-party reproduction of the 2025 FPSC paper; answer independently checked."
E26="Item in the 2026 file prepared by cssaspirants.pk on the FPSC pattern (not an original FPSC item); origin unconfirmed; answer independently checked."
items+=[
U("صنائع بدائع","Moderate",VP,2025,[],"اس شعر میں کون سی صنعت استعمال ہوئی ہے؟\nپوچھتے ہیں وہ کہ غالبؔ کون ہے\nکوئی بتلاؤ کہ ہم بتلائیں کیا",["تجاہلِ عارفانہ","اغراق","لف و نشر","صنعتِ تکرار"],"A","شاعر جان بوجھ کر انجان بن کر سوال کرتا ہے؛ اسے تجاہلِ عارفانہ کہتے ہیں۔",N25),
U("اصنافِ سخن","Moderate",VP,2025,[],"’’لاحول ولا قوۃ الا باللہ‘‘ شاعری کی کس صنف کا مشہور وزن ہے؟",["غزل","مرثیہ","رباعی","مثنوی"],"C","رباعی کے اوزان کی پہچان کے لیے یہی مصرع بطورِ وزن مشہور ہے۔",N25),
U("صنائع بدائع","Difficult",VP,2025,[],"علمِ بدیع کی کون سی صنعت اس شعر میں پائی جاتی ہے؟\nقیس صحرا میں اکیلا ہے مجھے جانے دو\nخوب گزرے گی جو مل بیٹھیں گے دیوانے دو",["صنعتِ تکرار","صنعتِ تضاد","صنعتِ لف و نشر","صنعتِ تجنیسِ تام"],"D","’’دو‘‘ (جانے دو) اور ’’دو‘‘ (دو دیوانے) — لفظ ایک، معنی مختلف؛ یہ تجنیسِ تام ہے۔",N25),
U("عروض","Moderate",VP,2025,[],"جس رکن اور بحر میں کوئی تغیر (زحاف) واقع نہ ہو، اسے عروضی اصطلاح میں کیا کہتے ہیں؟",["سالم","مثمن","طرفینِ استعارہ","وجہِ جامع"],"A","زحاف سے پاک رکن یا بحر کو سالم کہتے ہیں۔ ’’طرفینِ استعارہ‘‘ اور ’’وجہِ جامع‘‘ علمِ بیان کی اصطلاحیں ہیں۔",N25),
U("صنائع بدائع","Moderate",VP,2025,[],"صنعتِ طباق کا دوسرا نام کیا ہے؟",["صنعتِ مقابلہ","صنعتِ تضاد","صنعتِ ایہام","صنعتِ توریہ"],"B","جس کلام میں متضاد الفاظ جمع ہوں اسے طباق یا تضاد کہتے ہیں۔",N25),
U("قواعد","Easy",VP,2025,[],"’’دیوان‘‘ کی جمع کیا ہے؟",["دیوانے","دواوین","دیوانین","ان میں سے کوئی نہیں"],"B","’’دیوان‘‘ (مجموعۂ کلام) کی جمع دواوین ہے۔",N25),
U("قواعد","Easy",EQB,2026,[],"’’وارث‘‘ کی مؤنث کیا ہے؟",["وارثہ","وارثی","وراثت","ان میں سے کوئی نہیں"],"A","’’وارث‘‘ کی مؤنث وارثہ ہے؛ وراثت ترکے کو کہتے ہیں۔",E26),
U("قرآنی/اسلامی اصطلاحات","Difficult",EQB,2026,[],"قرآنِ مجید کی ابتدائی سات طویل سورتوں کو کیا کہتے ہیں؟",["سبع مثانی","سبع طوال","سبع معلقہ","ان میں سے کوئی نہیں"],"B","بقرہ سے توبہ/انفال تک کی ابتدائی سات طویل سورتیں سبع طوال کہلاتی ہیں؛ سبع مثانی عموماً سورۃ الفاتحہ ہے۔",E26+" Stem reworded by me (original said 'first seven revealed').") ,
U("الفاظ کے معنی","Easy",EQB,2026,[],"’’مائدہ‘‘ کا کیا مطلب ہے؟",["دسترخوان","پیالہ","چشمہ","ان میں سے کوئی نہیں"],"A","مائدہ عربی لفظ ہے، معنی: دسترخوان/خوانِ طعام (سورۃ المائدہ)۔",E26),
U("ادبیات","Moderate",EQB,2026,[],"نظم ’’مسجدِ قرطبہ‘‘ علامہ اقبال کے کس مجموعۂ کلام میں شامل ہے؟",["بانگِ درا","بالِ جبریل","ضربِ کلیم","ارمغانِ حجاز"],"B","’’مسجدِ قرطبہ‘‘ بالِ جبریل (1935) کی مشہور نظم ہے۔",E26),
U("محاورات","Moderate",EQB,2026,[],"محاورہ ’’تتر بتر ہونا‘‘ کا مطلب کیا ہے؟",["اکٹھا ہونا","بکھر جانا","خاموش ہونا","ان میں سے کوئی نہیں"],"B","’’تتر بتر ہونا‘‘ یعنی منتشر ہو جانا، بکھر جانا۔",E26),
U("اسلامی اصطلاحات","Difficult",EQB,2026,[],"وراثت میں ’’عصبات‘‘ سے کون سے رشتہ دار مراد ہیں؟",["ننھیالی رشتہ دار","مردانہ نسب والے رشتہ دار","سسرالی رشتہ دار","ان میں سے کوئی نہیں"],"B","عصبات باپ کی طرف سے مردانہ نسب والے وارث ہوتے ہیں جو مقررہ حصہ داروں کے بعد بچا ہوا ترکہ پاتے ہیں۔",E26),
U("قواعد","Easy",EQB,2026,[],"وہ اسم جو کسی نام کی جگہ استعمال ہو، اسے کیا کہتے ہیں؟",["اسمِ ظرف","اسمِ ضمیر","اسمِ صفت","ان میں سے کوئی نہیں"],"B","جو اسم کسی نام کے بدلے آئے (میں، تم، وہ) وہ اسمِ ضمیر ہے۔",E26),
U("ادبیات","Moderate",EQB,2026,[],"’’مقدمہ شعر و شاعری‘‘ کے مصنف کون ہیں؟",["سر سید احمد خان","الطاف حسین حالی","شبلی نعمانی","ان میں سے کوئی نہیں"],"B","مقدمہ شعر و شاعری مولانا الطاف حسین حالی کی تصنیف ہے جو ’’دیوانِ حالی‘‘ کے مقدمے کے طور پر لکھی گئی (1893)۔",E26),
U("دفتری اردو/ترجمہ","Moderate",EQB,2026,[],"’’Minutes of the Meeting‘‘ کا درست اردو متبادل کیا ہے؟",["روداد اجلاس","جلسے کے اوقات","پیش نامہ","اطلاع نامہ"],"A","اجلاس کی کارروائی کی تحریری رپورٹ کو روداد اجلاس کہتے ہیں۔",E26),
U("اصنافِ ادب","Easy",EQB,2026,[],"’’مثنوی‘‘ کا تعلق کس صنفِ ادب سے ہے؟",["نثر","شاعری","ڈراما","ان میں سے کوئی نہیں"],"B","مثنوی شاعری کی صنف ہے جس میں ہر شعر کے دونوں مصرعے ہم قافیہ ہوتے ہیں۔",E26),
U("متضاد","Easy",EQB,2026,[],"’’عروج‘‘ کا متضاد کیا ہے؟",["ترقی","زوال","بلندی","ان میں سے کوئی نہیں"],"B","عروج کا متضاد زوال ہے۔",E26),
U("زبان و بیان","Easy",EQB,2026,[],"اردو زبان کا رسم الخط (طرزِ تحریر) کون سا ہے؟",["نسخ","نستعلیق","کوفی","ان میں سے کوئی نہیں"],"B","اردو عموماً خطِ نستعلیق میں لکھی جاتی ہے۔",E26),
q(UR,"محاورات","Moderate",GP,None,[],"محاورہ ’’آسمان سے باتیں کرنا‘‘ کا مطلب کیا ہے؟",["آسمان کی طرف دیکھنا","بہت بلند ہونا","خوب بولنا","خاموش رہنا"],"B","’’آسمان سے باتیں کرنا‘‘ یعنی بہت اونچا ہونا (عمارت وغیرہ کے لیے)۔","Generated for this mock; Urdu wording should be read once by a native speaker."),
q(UR,"املا","Moderate",GP,None,[],"درست املا والا لفظ منتخب کیجیے:",["زہین","ذھین","ذہین","زھین"],"C","صحیح املا ’’ذہین‘‘ ہے (ذ سے، اور ’ہ‘ دو چشمی ھ نہیں)۔","Generated for this mock; Urdu wording should be read once by a native speaker."),
]
