from helpers import *
EN="English"
def E(topic,diff,src,year,also,stem,opts,ans,expl,note="",passage=None): return q(EN,topic,diff,src,year,also,stem,opts,ans,expl,note,passage)
N="Third-party reproduction of an FPSC paper; answer independently checked."
PASSAGE=("Yesterday, I was exposed to what has been called \"a dining experience like no other.\" At lunchtime, Dilly's Deli is so crowded, I wondered when the fire marshal had last visited the establishment. The line snaked out of the door to the corner, and by the time I reached the counter, I was freezing. I decided on the hamburger steak special; the other specials being liver and onions or tuna casserole. Each special is offered with two side dishes, but there was no potato salad left and the green beans were cooked nearly beyond recognition. I chose the gelatin of the day and what turned out to be the blandest coleslaw I have ever eaten. At Dilly's, you sit at one of four long tables. The couple sitting across from me was having an argument. The truck driver next to me told me more than I wanted to know about highway taxes. After I had tasted all of the food on my plate, I rose to leave, whereupon one of the people working behind the counter yelled at me to clean up after myself. Throwing away that plate of food was the most enjoyable part of dining at Dilly's.")
items=[
# --- synonyms / vocabulary
E("Synonyms","Moderate",VP,2025,[2026],"Catacomb:",["Oasis","Haven","Crypt","Shrine"],"C","A catacomb is an underground burial chamber; 'crypt' (an underground burial vault) is closest.",N),
E("Synonyms","Difficult",VP,2025,[2026],"Verisimilitude:",["Realism","Artifice","Conceit","Actuality"],"A","Verisimilitude is the appearance of being true or real; 'realism' is the closest synonym. 'Actuality' means real existence, not appearance of truth.",N),
E("Synonyms","Moderate",VP,2023,[],"Synonym of Pejorative:",["Laudatory","Complementary","Approbatory","Depreciatory"],"D","Pejorative means expressing contempt or disapproval; 'depreciatory' (belittling) matches. The others are praising words.",N),
E("Synonyms","Easy",VP,2023,[],"She showed a blatant disregard for the rules. (Synonym of the underlined word 'blatant')",["Obvious","Hidden","Last-minute","Rebellious"],"A","Blatant means done openly and unashamedly, i.e. obvious.",N),
E("Synonyms","Easy",VP,2023,[],"As soon as details of the election were released to the media, the newspaper was inundated with calls - far too many to be handled effectively. (Synonym of 'inundated')",["Provided","Bothered","Reminded","Flooded"],"D","Inundated means overwhelmed with a large quantity; 'flooded' is the synonym.",N),
E("Synonyms","Moderate",VP,2022,[],"SUMPTUOUS",["Delirious","Gorgeous","Perilous","Luxurious"],"D","Sumptuous means splendid and costly, hence luxurious. 'Gorgeous' refers to beauty, not expense.",N),
E("Synonyms","Difficult",VP,2022,[],"MORDANT",["Dead","Gruesome","Fetid","Caustic"],"D","Mordant means biting and sharp, especially of wit or criticism - caustic.",N),
E("Synonyms","Moderate",VP,2023,[],"'Argus-eyed' means:",["Watchful","Devoted","Lethargic","Clumsy"],"A","Argus, the hundred-eyed giant of Greek myth, never slept; 'argus-eyed' means vigilant.",N),
E("Synonyms","Moderate",VP,2023,[],"Dearth means:",["Scarcity","To punish or criticize severely","To cause, produce, or stir up","Habitually fond of associating in a company or herd"],"A","Dearth is a scarcity or lack of something.",N),
E("One-word Substitution","Easy",GP,None,[],"A person who can speak two languages fluently is called:",["polyglot","interpreter","linguist","bilingual"],"D","Bilingual = speaking two languages; a polyglot knows many; a linguist studies language.","Generated for this mock."),
# --- antonyms
E("Antonyms","Difficult",VP,2025,[2026],"Antonym of Bastion:",["Defenseless","Deformed","Destroyed","Demolished"],"A","A bastion is a stronghold or protected place; its opposite is a defenseless, unprotected one.",N),
E("Antonyms","Moderate",VP,2025,[2026],"Antonym of Melange:",["Harmonious","Homogeneous","Amorphous","Anomalous"],"B","A melange is a varied mixture; homogeneous means uniform throughout.",N),
E("Antonyms","Moderate",VP,2023,[],"Antonym of Cajole:",["Wheedle","Coax","Badger","Dissuade"],"D","To cajole is to persuade by flattery; to dissuade is to talk someone out of something.",N),
E("Antonyms","Easy",VP,2023,[],"Antonym of Ephemeral:",["Fleeting","Permanent","Transitory","Momentary"],"B","Ephemeral means short-lived; permanent is the opposite. The other three are synonyms.",N),
E("Antonyms","Moderate",VP,2023,[],"Antonym of Quixotic:",["Impulsive","Prosthetic","Dreamy","Practical"],"D","Quixotic means idealistic to an impractical degree; practical is the opposite.",N),
E("Antonyms","Moderate",VP,2022,[],"OBTUSE (antonym)",["Slim","Acute","Opaque","Thick"],"B","Obtuse (in the sense of slow to understand) is opposed to acute, meaning sharp-minded.",N),
# --- analogies
E("Analogies","Difficult",VP,2023,[],"Dependable : Capricious ::",["Fallible : Cantankerous","Capable : Inept","Malleable : Inept","Incorrigible : Guilty"],"B","The first pair are antonyms; capable and inept are also antonyms.",N),
E("Analogies","Moderate",VP,2022,[],"FROND : PALM ::",["quill : porcupine","blade : evergreen","scale : wallaby","tusk : alligator"],"A","A frond is the characteristic leaf-part of a palm; a quill is the characteristic spine of a porcupine.",N),
E("Analogies","Moderate",VP,2022,[],"DOLLAR : DIME ::",["Saleswoman : Pitch","Retreat : Victory","Century : Decade","Ring : Necklace"],"C","One dollar = 10 dimes; one century = 10 decades.",N),
E("Analogies","Moderate",VP,2022,[],"FERAL : TAME ::",["rancid : rational","nettlesome : annoying","repellent : honourable","ephemeral : immortal"],"D","Feral and tame are opposites; ephemeral (short-lived) and immortal are opposites.",N),
# --- sentence completion
E("Sentence Completion","Easy",VP,2022,[],"The settlers found an ideal location with plenty of ___ land for farming and a mountain stream for fresh water and irrigation.",["Arid","Quaint","Arable","Saline"],"C","Arable land is fit for growing crops.",N),
E("Sentence Completion","Moderate",VP,2022,[],"The defendant claimed that he was innocent and that his confession was:",["Flagrant","Coerced","Verity","Benign"],"B","Coerced means obtained by force or threats - consistent with claiming innocence.",N),
E("Sentence Completion","Moderate",VP,2022,[],"The rebel spies were charged with ___ and put on trial.",["Atrocity","Restoring","Sedition","Perilous"],"C","Sedition is conduct inciting rebellion against authority.",N),
E("Sentence Completion","Moderate",VP,2022,[],"Zachary was doomed to a miserable life, for no matter how much he had, he always ___ the possessions of others.",["Feasted","Exalted","Coveted","Filibustered"],"C","To covet is to desire what belongs to another.",N),
E("Sentence Completion","Easy",VP,2023,[],"His moral decadence was marked by his ______ from the ways of integrity and honesty.",["Obsession","Declivity","Opprobrium","Departure"],"D","'Departure from' the ways of integrity fits the sense and the preposition.",N),
# --- grammar / sentence correction
E("Sentence Correction","Moderate",VP,2025,[2026],"Choose the sentence that is grammatically correct.",["Walking down the street, the trees seemed to sway in the wind.","Walking down the street, I noticed the trees swaying in the wind.","Walking down the street, the wind caused the trees to sway.","Walking down the street, the swaying trees were noticed."],"B","The opening participle phrase must modify the person walking. Only (B) has 'I' as the subject; the others leave the modifier dangling.",N),
E("Subject-Verb Agreement","Moderate",VP,2026,[],"Choose the sentence that is grammatically correct.",["Neither of the boys have done his homework.","Neither of the boys has done his homework.","Neither of the boys have done their homeworks.","Neither of the boy has done his homework."],"B","'Neither' is singular, so it takes 'has'; 'homework' is uncountable, and 'of the boys' needs the plural 'boys'.",N),
E("Tenses","Easy",VP,2026,[],"Choose the sentence that is grammatically correct.",["She has been living here since five years.","She is living here for five years.","She has been living here for five years.","She lives here since five years."],"C","'For' is used with a period of time; 'since' needs a starting point; the present perfect continuous fits an action continuing up to now.",N),
E("Sentence Correction","Moderate",GP,2025,[2026],"Identify the sentence with a grammatical error.",["The new employee, along with the rest of the team, were responsible for the project's failure.","Having studied English for five years, I find the grammar rules easy.","The report, whose findings were groundbreaking, was published in a prestigious journal.","By the time the manager arrived, the employees had been working on the project for three hours."],"A","The subject is the singular 'employee' ('along with...' does not make it plural), so the verb should be 'was'.","Adapted from the 2025/2026 pattern; option (B) was rewritten because the original version contained a second error, so this is not counted as a past-paper item."),
E("Sentence Correction","Easy",VP,2026,[2025],"Identify the sentence with a semantic error.",["The dog chased its tail with a spoon.","The sun is shining in the sky.","The author is writing the book.","The rain is falling downwards."],"A","A dog chasing its tail 'with a spoon' is illogical; the other sentences are meaningful.",N),
E("Grammar","Easy",VP,2023,[],"Which of the following sentences is grammatically correct?",["I and my friends went to the movie.","My friends and I went to the movie.","Me and my friends went to the movie.","My friends and me went to the movie."],"B","'My friends and I' is the correct subject form, with the speaker named last.",N),
E("Grammar","Easy",VP,2023,[],"Which of the following is an example of a subordinate clause?",["I like pizza","Because I like pizza","Pizza is my favorite food","I ate pizza for dinner"],"B","A subordinate clause cannot stand alone; 'Because I like pizza' needs a main clause.",N),
E("Grammar","Easy",VP,2023,[],"Which sentence uses the correct adjective form?",["The movie was more scarier than I expected","The movie was scarier than I expected","The movie was scare than I expected","The movie was scary than I expected"],"B","The comparative of 'scary' is 'scarier'; 'more scarier' is a double comparative.",N),
E("Grammar","Easy",VP,2023,[],"Choose the correct sentence:",["All that is glitters is not gold","All that is glittering is not gold","All that glitters is not gold","All which glitters is not gold"],"C","The proverb is 'All that glitters is not gold'.",N),
E("Sentence Structure","Moderate",VP,2023,[],"\"Although they are 250 miles apart, they keep in constant contact on the internet.\" This is a:",["Simple sentence","Compound sentence","Complex sentence","Compound-complex sentence"],"C","One subordinate clause ('Although...') plus one main clause makes a complex sentence.",N),
# --- prepositions
E("Prepositions","Easy",VP,2023,[],"He was accused ______ theft.",["Of","In","With","None of these"],"A","'Accused of' is the correct collocation.",N),
E("Prepositions","Easy",VP,2023,[],"He writes ______ red ink.",["With","In","Of","By"],"B","'In red ink' is the idiomatic phrase for the medium or colour used.",N),
E("Prepositions","Difficult",VP,2022,[],"Ambition does not always conduce ___ ultimate happiness.",["Of","In","To","From"],"C","'Conduce to' means to lead or contribute to.",N),
E("Prepositions","Moderate",VP,2022,[],"He accepted the car in lieu ___ his claim.",["Of","With","For","Of, for"],"A","'In lieu of' means 'instead of'.",N),
E("Prepositions","Moderate",VP,2023,[],"He is so dull that he is insensible ______ the beauties of nature.",["For","To","Of","With"],"B","'Insensible to' means unaware of or unmoved by.",N),
# --- idioms
E("Idioms","Easy",VP,2025,[2026],"Forty winks means:",["A long, deep sleep","A short nap or brief period of sleep","A period of wakefulness","A dream or vision"],"B","'Forty winks' is a short nap.",N),
E("Idioms","Difficult",VP,2025,[2026],"To sell wolf tickets means:",["To be honest and authentic","To talk tough but not back it up","To be weak and timid","To be intelligent and wise"],"B","In American slang, selling wolf tickets means making empty, threatening boasts.",N),
# --- parts of speech
E("Parts of Speech","Moderate",VP,2022,[],"In the sentence 'Children love making mud castles', 'making' is:",["Verb","Main Verb","Gerund","Both (A) and (B)"],"C","'Making' is the verb-form used as a noun (the object of 'love'), i.e. a gerund.",N),
E("Parts of Speech","Easy",VP,2022,[],"Choose the sentence with a Proper Adjective.",["French wines are not available here","He showed much patience","He has lost all his strength","I ate some rice"],"A","'French' is derived from the proper noun France, so it is a proper adjective.",N),
E("Articles","Moderate",GP,None,[],"She is ___ MBA from a reputed university.",["a","the","an","no article is needed"],"C","The article depends on sound, not spelling: MBA begins with the vowel sound /em/, so 'an'.","Generated for this mock."),
E("Sentence Structure","Difficult",GP,None,[],"Hardly had he entered the room ___ the lights went out.",["as","then","than","when"],"D","'Hardly ... when' is the correct correlative pair (as with 'scarcely ... when'); 'than' goes with 'no sooner'.","Generated for this mock."),
# --- comprehension (Dilly's Deli)
E("Comprehension","Easy",VP,2026,[],"If you go to lunch at Dilly's Deli, you could expect to see:",["Couples dining together","The fire marshal","A long line of customers","Homemade pie"],"C","The writer says the line snaked out of the door to the corner.",N,PASSAGE),
E("Comprehension","Moderate",VP,2026,[],"Which of the following illustrates the restaurant critic's opinion of the food at Dilly's Deli?",["\"At Dilly's, you sit at one of four long tables.\"","\"At lunchtime, Dilly's Deli is so crowded, I wondered when the fire marshal had last visited the establishment.\"","\"After I had tasted all of the food on my plate, I rose to leave, whereupon one of the people working behind the counter yelled at me to clean up after myself.\"","\"Throwing away that plate of food was the most enjoyable part of dining at Dilly's.\""],"D","Only the last sentence directly states a judgment of the food.",N,PASSAGE),
E("Comprehension","Moderate",VP,2026,[],"The role of the 'fire marshal' mentioned in the passage appears to be:",["Checking the hygienic condition in the restaurant","Checking overcrowding at public places","Ensuring disciplined conduct of the restaurant's staff","None of these"],"B","The writer wonders when the marshal last visited because the place was dangerously crowded; fire marshals enforce occupancy limits.",N,PASSAGE),
]
items.insert(9,E("Synonyms","Difficult",VP,2023,[],"Synonym of Obdurate:",["Trustable","Malleable","Amenable","None of these"],"D","Obdurate means stubbornly refusing to change; malleable and amenable are its opposites, so none of the listed words is a synonym.",N))
