// Auto-generated by tools/teacher/build_teacher.py - do not edit by hand.
// Counts only, so landing pages can show bank sizes without downloading the questions.
export interface ExamStats { total: number; bySource: Record<string, number>; byDifficulty: Record<string, number>; bySubject: Record<string, number>; topics: Record<string, Record<string, number>>; shared: number }
export const BANK_STATS: { pst: ExamStats; jest: ExamStats; jst: ExamStats; unique: number } = {
 "pst": {
  "total": 541,
  "bySource": {
   "generated_syllabus": 506,
   "existing_question": 35
  },
  "byDifficulty": {
   "easy": 217,
   "moderate": 218,
   "difficult": 106
  },
  "bySubject": {
   "Computer": 43,
   "English": 120,
   "Islamiat": 52,
   "Social Studies": 54,
   "Science": 93,
   "Mathematics": 89,
   "Urdu": 90
  },
  "topics": {
   "Computer": {
    "Computer Fundamentals": 8,
    "Hardware": 5,
    "Software": 3,
    "Operating Systems": 3,
    "Input and Output Devices": 2,
    "Storage": 4,
    "Internet": 5,
    "Networking Basics": 2,
    "MS Office": 6,
    "Digital Literacy": 2,
    "Cybersecurity Awareness": 3
   },
   "English": {
    "Synonyms": 11,
    "Antonyms": 9,
    "Vocabulary": 6,
    "One-Word Substitution": 8,
    "Idioms": 9,
    "Tenses": 6,
    "Articles": 4,
    "Prepositions": 10,
    "Pronouns": 4,
    "Adjectives": 2,
    "Adverbs": 2,
    "Subject-Verb Agreement": 4,
    "Sentence Correction": 4,
    "Active and Passive Voice": 3,
    "Direct and Indirect Speech": 3,
    "Parts of Speech": 8,
    "Sentence Completion": 9,
    "Grammar": 7,
    "Reading Comprehension": 8,
    "Literature Basics": 3
   },
   "Islamiat": {
    "Quran": 11,
    "Seerah": 9,
    "Khulafa-e-Rashideen": 5,
    "Hadith": 3,
    "Prophets": 5,
    "Pillars of Islam": 7,
    "Basic Beliefs": 5,
    "Islamic Terminology": 2,
    "Important Islamic Events": 1,
    "Islamic History": 1,
    "Islamic Ethics": 3
   },
   "Social Studies": {
    "Pakistan Geography": 11,
    "History": 4,
    "Provinces": 6,
    "National Symbols": 7,
    "Constitution and Civics": 4,
    "Culture": 3,
    "Important Places": 4,
    "Geography of Sindh": 6,
    "Independence Movement": 4,
    "Important Personalities": 5
   },
   "Science": {
    "Biology Basics": 5,
    "Plants": 9,
    "Animals": 8,
    "Human Body": 14,
    "Environment": 7,
    "Matter": 8,
    "Force and Motion": 5,
    "Energy": 4,
    "Heat": 4,
    "Light": 4,
    "Sound": 4,
    "Electricity": 4,
    "Earth and Space": 7,
    "Everyday Science": 6,
    "General Science": 4
   },
   "Mathematics": {
    "Basic Arithmetic": 8,
    "Number Systems": 5,
    "Factors and Multiples": 5,
    "Fractions": 7,
    "Decimals": 4,
    "Percentages": 7,
    "Ratio and Proportion": 5,
    "Average": 3,
    "Profit and Loss": 4,
    "Simple Interest": 3,
    "Time and Work": 2,
    "Time, Speed and Distance": 3,
    "Basic Algebra": 7,
    "Geometry": 6,
    "Mensuration": 7,
    "Data Handling": 4,
    "Word Problems": 5,
    "Mathematical Reasoning": 4
   },
   "Urdu": {
    "Idioms": 9,
    "Synonyms": 17,
    "Antonyms": 19,
    "Singular and Plural": 10,
    "Meaning": 8,
    "Grammar": 8,
    "Masculine and Feminine": 9,
    "Spelling": 4,
    "Sentence Structure": 2,
    "Comprehension": 3,
    "Vocabulary": 1
   }
  },
  "shared": 363
 },
 "jest": {
  "total": 688,
  "bySource": {
   "generated_syllabus": 605,
   "existing_question": 83
  },
  "byDifficulty": {
   "easy": 157,
   "moderate": 386,
   "difficult": 145
  },
  "bySubject": {
   "Computer": 55,
   "English": 179,
   "Mathematics": 155,
   "Social Studies": 76,
   "Science": 123,
   "Pedagogy": 100
  },
  "topics": {
   "Computer": {
    "Computer Fundamentals": 15,
    "Hardware and Software": 9,
    "Operating Systems": 4,
    "Internet": 6,
    "Networking": 4,
    "MS Office": 7,
    "Information Technology": 4,
    "Cybersecurity Basics": 4,
    "Database Basics": 2
   },
   "English": {
    "Synonyms and Antonyms": 37,
    "Vocabulary": 10,
    "One-Word Substitution": 12,
    "Idioms": 13,
    "Tenses": 8,
    "Articles": 5,
    "Prepositions": 16,
    "Grammar": 31,
    "Subject-Verb Agreement": 7,
    "Sentence Correction": 8,
    "Error Detection": 2,
    "Voice": 4,
    "Narration": 4,
    "Sentence Completion": 14,
    "Comprehension": 8
   },
   "Mathematics": {
    "Profit and Loss": 8,
    "Arithmetic": 48,
    "Averages": 8,
    "Percentages": 12,
    "Ratios": 10,
    "Mensuration": 13,
    "Probability": 5,
    "Interest": 5,
    "Algebra": 10,
    "Linear Equations": 3,
    "Geometry": 10,
    "Statistics": 6,
    "Sets and Relations": 3,
    "Word Problems": 7,
    "Mathematical Reasoning": 7
   },
   "Social Studies": {
    "Geography": 24,
    "Pakistan History": 14,
    "Culture": 10,
    "Constitution": 5,
    "Sindh History and Geography": 10,
    "Important Personalities": 7,
    "Civics": 1,
    "Economy Basics": 3,
    "National Events": 2
   },
   "Science": {
    "Biology": 14,
    "Plants": 10,
    "Human Biology": 14,
    "Ecology": 9,
    "Matter": 8,
    "Force": 7,
    "Energy": 5,
    "Physics": 5,
    "Light": 6,
    "Sound": 5,
    "Electricity": 7,
    "Earth and Space": 8,
    "Everyday Science": 7,
    "General Science": 6,
    "Cells": 4,
    "Chemistry": 4,
    "Chemical Reactions": 2,
    "Motion": 2
   },
   "Pedagogy": {
    "Learning Styles (VARK)": 10,
    "Cognitive, Physical and Social Differences": 10,
    "Lesson Planning and SLOs": 10,
    "Teaching Skills": 10,
    "Teaching Methodology": 10,
    "Use of ICT in the Classroom": 10,
    "Assessment and Evaluation": 10,
    "Reflective Practice and Feedback": 10,
    "Classroom Management": 10,
    "STEAM/STREAM and Project-Based Learning": 10
   }
  },
  "shared": 650
 },
 "jst": {
  "total": 879,
  "bySource": {
   "generated_syllabus": 799,
   "existing_question": 80
  },
  "byDifficulty": {
   "easy": 206,
   "moderate": 445,
   "difficult": 228
  },
  "bySubject": {
   "Computer": 92,
   "English": 185,
   "Mathematics": 200,
   "Social Studies": 76,
   "Science": 226,
   "Pedagogy": 100
  },
  "topics": {
   "Computer": {
    "Introduction to Computers and Types": 33,
    "Operating System": 7,
    "Computer Networking": 16,
    "Office Automation": 10,
    "Cyber-Attacks and Ethical Hacking": 10,
    "Database Management System": 7,
    "Generations of Computers": 4,
    "Web Development": 5
   },
   "English": {
    "Vocabulary": 86,
    "Tenses": 8,
    "Parts of Speech": 69,
    "Active and Passive Voice": 4,
    "Direct and Indirect Speech": 4,
    "Punctuation": 6,
    "Reading Comprehension": 8
   },
   "Mathematics": {
    "Financial Arithmetic and Consumer Math": 10,
    "Time": 14,
    "Central Tendency": 18,
    "Ratio, Rate and Percentage": 40,
    "Surface Area and Volume": 27,
    "Probability": 7,
    "Multiples and Factors": 19,
    "Prime and Composite": 9,
    "Simple and Compound Interest": 8,
    "Expressions": 13,
    "Equations and Inequalities": 16,
    "Coordinate Geometry": 5,
    "Patterns": 10,
    "Ratio Conversion": 2,
    "Percentage Expansion": 2
   },
   "Social Studies": {
    "Social Studies": 46,
    "Pakistan Studies": 30
   },
   "Science": {
    "Biology: Cell Structure": 12,
    "Biology: Cell Division": 3,
    "Biology: Respiration": 4,
    "Biology: Enzymes": 4,
    "Biology: Types of Living Organisms": 11,
    "Biology: Tissues, Organs and Systems": 23,
    "Biology: Evolution": 9,
    "Biology: Ecosystem": 8,
    "Chemistry: Elements, Compounds and Mixtures": 3,
    "Chemistry: Thermochemistry": 3,
    "Chemistry: Environmental Chemistry": 3,
    "Chemistry: Mole and Molarity": 3,
    "Chemistry: Acids and Bases": 10,
    "Chemistry: Equilibrium": 3,
    "Chemistry: Chemical Reactions": 10,
    "Chemistry: Industrial Chemistry": 9,
    "Chemistry: Electrochemistry": 3,
    "Chemistry: Kinetics": 3,
    "Chemistry: Solutions and Suspensions": 3,
    "Physics: Mechanics": 20,
    "Physics: Thermal Physics": 11,
    "Physics: Waves": 7,
    "Physics: Electromagnetism": 13,
    "Physics: Atomic Physics and Optics": 11,
    "Physics: Nuclear Physics": 7,
    "Physics: Electronics": 6,
    "Chemistry: Atomic Structure": 8,
    "Chemistry: Periodic Table": 6,
    "Chemistry: Bonding": 5,
    "Chemistry: States of Matter": 5
   },
   "Pedagogy": {
    "Learning Styles (VARK)": 10,
    "Cognitive, Physical and Social Differences": 10,
    "Lesson Planning and SLOs": 10,
    "Teaching Skills": 10,
    "Teaching Methodology": 10,
    "Use of ICT in the Classroom": 10,
    "Assessment and Evaluation": 10,
    "Reflective Practice and Feedback": 10,
    "Classroom Management": 10,
    "STEAM/STREAM and Project-Based Learning": 10
   }
  },
  "shared": 565
 },
 "unique": 1180
};
