// Auto-generated by tools/teacher/build_teacher.py - do not edit by hand.
// Counts only, so landing pages can show bank sizes without downloading the questions.
export interface ExamStats { total: number; bySource: Record<string, number>; byDifficulty: Record<string, number>; bySubject: Record<string, number>; topics: Record<string, Record<string, number>>; shared: number }
export const BANK_STATS: { pst: ExamStats; jest: ExamStats; jst: ExamStats; unique: number } = {
 "pst": {
  "total": 541,
  "bySource": {
   "generated_syllabus": 506,
   "existing_question": 35
  },
  "byDifficulty": {
   "easy": 217,
   "moderate": 218,
   "difficult": 106
  },
  "bySubject": {
   "Computer": 43,
   "English": 120,
   "Islamiat": 52,
   "Social Studies": 54,
   "Science": 93,
   "Mathematics": 89,
   "Urdu": 90
  },
  "topics": {
   "Computer": {
    "Computer Fundamentals": 8,
    "Hardware": 5,
    "Software": 3,
    "Operating Systems": 3,
    "Input and Output Devices": 2,
    "Storage": 4,
    "Internet": 5,
    "Networking Basics": 2,
    "MS Office": 6,
    "Digital Literacy": 2,
    "Cybersecurity Awareness": 3
   },
   "English": {
    "Synonyms": 11,
    "Antonyms": 9,
    "Vocabulary": 6,
    "One-Word Substitution": 8,
    "Idioms": 9,
    "Tenses": 6,
    "Articles": 4,
    "Prepositions": 10,
    "Pronouns": 4,
    "Adjectives": 2,
    "Adverbs": 2,
    "Subject-Verb Agreement": 4,
    "Sentence Correction": 4,
    "Active and Passive Voice": 3,
    "Direct and Indirect Speech": 3,
    "Parts of Speech": 8,
    "Sentence Completion": 9,
    "Grammar": 7,
    "Reading Comprehension": 8,
    "Literature Basics": 3
   },
   "Islamiat": {
    "Quran": 11,
    "Seerah": 9,
    "Khulafa-e-Rashideen": 5,
    "Hadith": 3,
    "Prophets": 5,
    "Pillars of Islam": 7,
    "Basic Beliefs": 5,
    "Islamic Terminology": 2,
    "Important Islamic Events": 1,
    "Islamic History": 1,
    "Islamic Ethics": 3
   },
   "Social Studies": {
    "Pakistan Geography": 11,
    "History": 4,
    "Provinces": 6,
    "National Symbols": 7,
    "Constitution and Civics": 4,
    "Culture": 3,
    "Important Places": 4,
    "Geography of Sindh": 6,
    "Independence Movement": 4,
    "Important Personalities": 5
   },
   "Science": {
    "Biology Basics": 5,
    "Plants": 9,
    "Animals": 8,
    "Human Body": 14,
    "Environment": 7,
    "Matter": 8,
    "Force and Motion": 5,
    "Energy": 4,
    "Heat": 4,
    "Light": 4,
    "Sound": 4,
    "Electricity": 4,
    "Earth and Space": 7,
    "Everyday Science": 6,
    "General Science": 4
   },
   "Mathematics": {
    "Basic Arithmetic": 8,
    "Number Systems": 5,
    "Factors and Multiples": 5,
    "Fractions": 7,
    "Decimals": 4,
    "Percentages": 7,
    "Ratio and Proportion": 5,
    "Average": 3,
    "Profit and Loss": 4,
    "Simple Interest": 3,
    "Time and Work": 2,
    "Time, Speed and Distance": 3,
    "Basic Algebra": 7,
    "Geometry": 6,
    "Mensuration": 7,
    "Data Handling": 4,
    "Word Problems": 5,
    "Mathematical Reasoning": 4
   },
   "Urdu": {
    "Idioms": 9,
    "Synonyms": 17,
    "Antonyms": 19,
    "Singular and Plural": 10,
    "Meaning": 8,
    "Grammar": 8,
    "Masculine and Feminine": 9,
    "Spelling": 4,
    "Sentence Structure": 2,
    "Comprehension": 3,
    "Vocabulary": 1
   }
  },
  "shared": 500
 },
 "jest": {
  "total": 774,
  "bySource": {
   "generated_syllabus": 676,
   "existing_question": 98
  },
  "byDifficulty": {
   "easy": 183,
   "moderate": 442,
   "difficult": 149
  },
  "bySubject": {
   "Computer": 55,
   "English": 179,
   "Islamiat": 79,
   "Mathematics": 155,
   "Social Studies": 76,
   "Science": 123,
   "Urdu": 107
  },
  "topics": {
   "Computer": {
    "Computer Fundamentals": 15,
    "Hardware and Software": 9,
    "Operating Systems": 4,
    "Internet": 6,
    "Networking": 4,
    "MS Office": 7,
    "Information Technology": 4,
    "Cybersecurity Basics": 4,
    "Database Basics": 2
   },
   "English": {
    "Synonyms and Antonyms": 37,
    "Vocabulary": 10,
    "One-Word Substitution": 12,
    "Idioms": 13,
    "Tenses": 8,
    "Articles": 5,
    "Prepositions": 16,
    "Grammar": 31,
    "Subject-Verb Agreement": 7,
    "Sentence Correction": 8,
    "Error Detection": 2,
    "Voice": 4,
    "Narration": 4,
    "Sentence Completion": 14,
    "Comprehension": 8
   },
   "Islamiat": {
    "Seerah": 18,
    "Quran": 14,
    "Khulafa": 7,
    "Hadith": 5,
    "Islamic Personalities": 7,
    "Islamic Concepts": 15,
    "Jurisprudence Basics": 2,
    "Battles and Events": 3,
    "Islamic History": 1,
    "Islamic Civilization": 3,
    "Ethics and Social Principles": 4
   },
   "Mathematics": {
    "Profit and Loss": 8,
    "Arithmetic": 48,
    "Averages": 8,
    "Percentages": 12,
    "Ratios": 10,
    "Mensuration": 13,
    "Probability": 5,
    "Interest": 5,
    "Algebra": 10,
    "Linear Equations": 3,
    "Geometry": 10,
    "Statistics": 6,
    "Sets and Relations": 3,
    "Word Problems": 7,
    "Mathematical Reasoning": 7
   },
   "Social Studies": {
    "Geography": 24,
    "Pakistan History": 14,
    "Culture": 10,
    "Constitution": 5,
    "Sindh History and Geography": 10,
    "Important Personalities": 7,
    "Civics": 1,
    "Economy Basics": 3,
    "National Events": 2
   },
   "Science": {
    "Biology": 14,
    "Plants": 10,
    "Human Biology": 14,
    "Ecology": 9,
    "Matter": 8,
    "Force": 7,
    "Energy": 5,
    "Physics": 5,
    "Light": 6,
    "Sound": 5,
    "Electricity": 7,
    "Earth and Space": 8,
    "Everyday Science": 7,
    "General Science": 6,
    "Cells": 4,
    "Chemistry": 4,
    "Chemical Reactions": 2,
    "Motion": 2
   },
   "Urdu": {
    "Idioms": 12,
    "Synonyms and Antonyms": 36,
    "Grammar": 30,
    "Vocabulary": 10,
    "Correct Usage": 6,
    "Sentence Correction": 1,
    "Comprehension": 3,
    "Literature": 6,
    "Translation": 3
   }
  },
  "shared": 736
 },
 "jst": {
  "total": 804,
  "bySource": {
   "generated_syllabus": 709,
   "existing_question": 95
  },
  "byDifficulty": {
   "easy": 192,
   "moderate": 430,
   "difficult": 182
  },
  "bySubject": {
   "Computer": 60,
   "English": 179,
   "Islamiat": 79,
   "Mathematics": 155,
   "Social Studies": 76,
   "Urdu": 107,
   "Science": 148
  },
  "topics": {
   "Computer": {
    "Computer Fundamentals": 16,
    "Hardware and Software": 10,
    "Operating Systems": 5,
    "Internet": 7,
    "Networking": 5,
    "MS Office": 7,
    "Information Technology": 4,
    "Cybersecurity Basics": 4,
    "Database Basics": 2
   },
   "English": {
    "Synonyms and Antonyms": 37,
    "Vocabulary": 36,
    "Idioms": 13,
    "Grammar": 75,
    "Sentence Correction": 10,
    "Comprehension": 8
   },
   "Islamiat": {
    "Seerah": 18,
    "Quran": 14,
    "Khulafa": 7,
    "Hadith": 5,
    "Islamic Personalities": 7,
    "Islamic Concepts": 15,
    "Jurisprudence Basics": 2,
    "Battles and Events": 3,
    "Islamic History": 1,
    "Islamic Civilization": 3,
    "Ethics and Social Principles": 4
   },
   "Mathematics": {
    "Arithmetic": 91,
    "Mensuration": 13,
    "Statistics and Probability": 11,
    "Algebra": 16,
    "Geometry": 10,
    "Word Problems": 7,
    "Mathematical Reasoning": 7
   },
   "Social Studies": {
    "Geography": 24,
    "Pakistan History": 14,
    "Culture": 10,
    "Constitution": 5,
    "Sindh History and Geography": 10,
    "Important Personalities": 7,
    "Civics": 1,
    "Economy Basics": 3,
    "National Events": 2
   },
   "Urdu": {
    "Idioms": 12,
    "Synonyms and Antonyms": 36,
    "Grammar": 30,
    "Vocabulary": 10,
    "Correct Usage": 6,
    "Sentence Correction": 1,
    "Comprehension": 3,
    "Literature": 6,
    "Translation": 3
   },
   "Science": {
    "Physics: Mechanics": 16,
    "Physics: Heat and Thermodynamics": 8,
    "Physics: Light and Optics": 7,
    "Physics: Sound and Waves": 5,
    "Physics: Electricity and Magnetism": 9,
    "Physics: Modern Physics": 5,
    "Chemistry: Atomic Structure": 8,
    "Chemistry: Periodic Table": 6,
    "Chemistry: Chemical Bonding": 5,
    "Chemistry: Reactions and Stoichiometry": 9,
    "Chemistry: Acids, Bases and Salts": 8,
    "Chemistry: Organic Basics": 6,
    "Chemistry: States of Matter": 5,
    "Biology: Cell Biology": 9,
    "Biology: Human Physiology": 12,
    "Biology: Plant Biology": 8,
    "Biology: Genetics and Evolution": 7,
    "Biology: Ecology and Environment": 7,
    "Biology: Microorganisms and Health": 8
   }
  },
  "shared": 651
 },
 "unique": 968
};
