export type Base = "A" | "T" | "C" | "G";

export interface Feedback {
  index: number;
  status: "correct" | "incorrect";
}

export interface DnaState {
  /** The given (top) strand — regenerated by "New Sequence". */
  sequence: Base[];
  /** The student-built complementary (bottom) strand; null = not yet answered. */
  filled: (Base | null)[];
  /** Which position is currently highlighted — either awaiting an answer or just clicked to see its pairing. */
  selectedIndex: number | null;
  /** Transient result of the last answer attempt, shown near the base buttons. */
  feedback: Feedback | null;
}
