from helpers import q, qf
K = "Computer"
rows = [
q("PJ",K,"Computer Fundamentals","e","The brain of the computer is the:","CPU",["monitor","keyboard","printer"],"The central processing unit executes instructions."),
q("PJ",K,"Computer Fundamentals","e","Which of the following is an input device?","keyboard",["monitor","speaker","printer"],"A keyboard sends data into the computer."),
q("P",K,"Computer Fundamentals","e","The full form of PC is:","Personal Computer",["Portable Calculator","Printed Circuit","Public Computer"],"PC stands for Personal Computer."),
q("PJ",K,"Computer Fundamentals","m","One byte consists of:","8 bits",["4 bits","16 bits","10 bits"],"A byte is a group of eight bits."),
q("PJ",K,"Computer Fundamentals","m","Which number system is used internally by computers?","binary",["decimal","octal only","roman"],"Computers store and process data as 0s and 1s."),
q("J",K,"Computer Fundamentals","d","The binary number 1011 is equal to which decimal number?","11",["13","9","15"],"8 + 0 + 2 + 1 = 11.",chk=int("1011",2)),
q("J",K,"Computer Fundamentals","d","Which of the following is the largest unit of data?","terabyte",["gigabyte","megabyte","kilobyte"],"1 TB = 1024 GB."),
q("PJ",K,"Hardware","e","Which device is used to point and click on the screen?","mouse",["scanner","speaker","modem"],"A mouse controls the pointer."),
q("PJ",K,"Hardware","m","Which part of the computer is also called its 'main memory'?","RAM",["hard disk","ROM only","CPU cache only"],"RAM holds the data and programs currently in use."),
q("PJ",K,"Hardware","m","The motherboard is:","the main circuit board of the computer",["a type of monitor","a type of software","a storage disk"],"All major components connect to it."),
q("J",K,"Hardware and Software","d","Which memory is volatile (loses data when power is off)?","RAM",["ROM","hard disk","SSD"],"RAM needs power to hold data."),
q("PJ",K,"Software","e","Microsoft Word is an example of:","application software",["system software","hardware","firmware"],"Word is an application program for writing documents."),
q("PJ",K,"Software","m","Which of the following is system software?","operating system",["Microsoft Excel","Adobe Photoshop","a web browser"],"System software manages the hardware and runs other programs."),
q("PJ",K,"Operating Systems","e","Which of these is an operating system?","Windows",["Chrome","Word","Excel"],"Windows is an operating system."),
q("PJ",K,"Operating Systems","m","Android is an operating system mostly used on:","mobile phones",["mainframes only","printers","calculators"],"Android is a mobile operating system."),
q("J",K,"Operating Systems","d","Which of the following is a function of an operating system?","memory management",["spell checking","drawing pictures","typing letters"],"The operating system allocates memory to programs."),
q("PJ",K,"Input and Output Devices","e","A printer is an example of:","an output device",["an input device","a storage device","a processing device"],"A printer produces output on paper."),
q("PJ",K,"Input and Output Devices","m","Which device is used to convert a paper document into a digital image?","scanner",["plotter","projector","joystick"],"A scanner captures images of paper documents."),
q("PJ",K,"Storage","e","Which of these is a storage device?","USB flash drive",["mouse","monitor","keyboard"],"A flash drive stores data."),
q("PJ",K,"Storage","m","Which of the following has the greatest storage capacity?","hard disk",["floppy disk","CD","DVD"],"Modern hard disks store hundreds of gigabytes to terabytes."),
q("PJ",K,"Internet","e","WWW stands for:","World Wide Web",["World Web Window","Wide World Web","Web World Wide"],"WWW is the World Wide Web."),
q("PJ",K,"Internet","m","Which of the following is a web browser?","Mozilla Firefox",["Microsoft Excel","Windows","Notepad"],"A browser opens websites."),
q("PJ",K,"Internet","m","An email address always contains the symbol:","@",["#","&","%"],"The @ separates the user name from the domain."),
q("J",K,"Internet","d","The protocol used for transferring web pages is:","HTTP",["SMTP","FTP","POP3"],"HTTP carries web pages; SMTP and POP3 are for e-mail."),
q("PJ",K,"Networking Basics","m","A network that covers a small area such as a school is a:","LAN",["WAN","MAN","PAN only"],"A local area network covers a small area."),
q("J",K,"Networking","d","The device that connects a local network to the internet is called a:","router",["scanner","plotter","joystick"],"A router forwards data between networks."),
q("J",K,"Networking","d","An IP address is used to:","identify a device on a network",["clean the computer","speed up the printer","store web pages"],"Each device on a network has an address."),
q("PJ",K,"MS Office","e","Which MS Office program is used to create spreadsheets?","Excel",["Word","PowerPoint","Paint"],"Excel is a spreadsheet program."),
q("PJ",K,"MS Office","e","Which program is used to make presentations?","PowerPoint",["Excel","Access","Notepad"],"PowerPoint creates slide shows."),
q("PJ",K,"MS Office","m","What is the shortcut key to copy selected text?","Ctrl + C",["Ctrl + V","Ctrl + X","Ctrl + Z"],"Ctrl+C copies, Ctrl+V pastes, Ctrl+X cuts and Ctrl+Z undoes."),
q("PJ",K,"MS Office","m","In Excel, a cell address is given by:","a column letter and a row number",["a row number only","a sheet name only","a file name"],"For example B3 is column B, row 3."),
q("J",K,"MS Office","d","In Excel, the formula =SUM(A1:A5) will:","add the values in cells A1 to A5",["count the cells","find the largest value","multiply the values"],"SUM adds the values in the range."),
q("PJ",K,"Digital Literacy","m","Which file extension is used for a Microsoft Word document?",".docx",[".xlsx",".pptx",".txt only"],"Word documents are saved as .docx."),
q("PJ",K,"Cybersecurity Awareness","e","Which of these is the best password?","a mix of letters, numbers and symbols",["your name","12345","your date of birth"],"A long mixed password is harder to guess."),
q("PJ",K,"Cybersecurity Awareness","m","A program designed to damage or disrupt a computer is called:","malware",["freeware","firmware","shareware"],"Viruses, worms and ransomware are malware."),
q("J",K,"Cybersecurity Basics","d","Pretending to be a trusted organisation in an e-mail to steal passwords is called:","phishing",["spamming only","debugging","booting"],"Phishing tricks users into revealing information."),
q("J",K,"Database Basics","m","A collection of related data organised in tables is called a:","database",["spreadsheet cell","browser","compiler"],"A database stores structured data."),
q("J",K,"Database Basics","d","In a database table, a row is also called a:","record",["field","key only","query"],"Each row is one record; each column is a field."),
q("J",K,"Information Technology","m","IT stands for:","Information Technology",["Internet Telephone","Internal Task","Integrated Tool"],"IT is Information Technology."),
q("J",K,"Information Technology","d","Cloud storage means data is stored:","on remote servers accessed over the internet",["only on the hard disk","only on a CD","only in RAM"],"Examples are Google Drive and OneDrive."),
q("S",K,"Computer Fundamentals","m","The binary equivalent of the decimal number 13 is:","1101",["1011","1110","1001"],"13 = 8 + 4 + 1 = 1101.",chk=bin(13)[2:]),
q("S",K,"Operating Systems","m","Which of these is a computer's file management feature?","creating folders",["adding noise","printing only","scanning only"],"Folders organise files in the operating system."),
q("S",K,"Networking","d","Which of the following is a private IP address?","192.168.1.5",["8.8.8.8","172.217.0.1","1.1.1.1"],"192.168.x.x is reserved for private networks; the others are public."),
q("S",K,"Hardware and Software","m","Which memory is permanent and holds the start-up instructions of a computer?","ROM",["RAM","cache","register"],"Read-only memory keeps its contents without power."),
q("S",K,"Internet","e","Which of these is a search engine?","Google",["Outlook","Excel","Paint"],"Google is a search engine."),
]
