from helpers import q, qf
E = "English"
rows = [
# ---- Synonyms
q("PJ",E,"Synonyms","e","Choose the word closest in meaning to 'ancient'.","old",["modern","fragile","empty"],"Ancient describes something from a very long time ago, so 'old' is the closest."),
q("PJ",E,"Synonyms","e","Choose the synonym of 'brave'.","courageous",["timid","careless","gentle"],"A brave person shows courage, so 'courageous' means the same."),
q("PJ",E,"Synonyms","e","Which word means the same as 'huge'?","enormous",["narrow","ordinary","distant"],"Huge and enormous both mean extremely large."),
q("P",E,"Synonyms","e","The synonym of 'begin' is:","commence",["conclude","delay","avoid"],"To commence is to begin."),
q("P",E,"Synonyms","e","Choose the word that means 'to help'.","assist",["resist","insist","consist"],"Assist means to help; the other words only look similar."),
q("PJ",E,"Synonyms","m","Choose the synonym of 'diligent'.","hardworking",["forgetful","talkative","wealthy"],"A diligent person works with steady, careful effort, so 'hardworking' is closest."),
q("PJ",E,"Synonyms","m","Which word is closest in meaning to 'scarce'?","rare",["plentiful","costly","bitter"],"Scarce means not enough in supply, so 'rare' fits."),
q("PJ",E,"Synonyms","m","Choose the synonym of 'reluctant'.","unwilling",["eager","careful","loyal"],"Reluctant means not wanting to do something, the same as unwilling."),
q("J",E,"Synonyms","m","'The committee decided to postpone the meeting.' The word closest in meaning to 'postpone' is:","defer",["cancel","advance","conduct"],"To postpone is to put off until a later time; defer means the same. Cancel ends it altogether."),
q("PJ",E,"Synonyms","m","Choose the synonym of 'abundant'.","plentiful",["limited","useless","ancient"],"Abundant means existing in large quantities, i.e. plentiful."),
q("J",E,"Synonyms","d","Choose the word closest in meaning to 'candid'.","frank",["secretive","polite","hesitant"],"A candid remark is honest and direct, so 'frank' is the closest."),
q("JS",E,"Synonyms","d","Choose the synonym of 'meticulous'.","careful about every detail",["quickly finished","often mistaken","easily annoyed"],"Meticulous describes extreme attention to detail."),
q("JS",E,"Synonyms","d","'His frugal habits helped him save money.' 'Frugal' is closest in meaning to:","thrifty",["generous","lazy","reckless"],"Frugal means careful with money, i.e. thrifty."),
q("J",E,"Synonyms","d","Choose the synonym of 'ephemeral'.","short-lived",["everlasting","dangerous","shiny"],"Ephemeral things last only a very short time."),
q("JS",E,"Synonyms","d","Choose the word closest in meaning to 'obsolete'.","out of date",["newly invented","very costly","hard to find"],"Obsolete means no longer in use because something newer has replaced it."),
# ---- Antonyms
q("PJ",E,"Antonyms","e","Choose the antonym of 'victory'.","defeat",["success","triumph","win"],"Victory is winning; its opposite is defeat."),
q("PJ",E,"Antonyms","e","The opposite of 'expand' is:","shrink",["grow","spread","stretch"],"To expand is to become larger; to shrink is to become smaller."),
q("P",E,"Antonyms","e","Choose the antonym of 'generous'.","selfish",["kind","helpful","rich"],"A generous person gives freely; a selfish person does not."),
q("P",E,"Antonyms","e","The opposite of 'ancient' is:","modern",["old","historic","dusty"],"Ancient means very old; modern means of the present time."),
q("PJ",E,"Antonyms","m","Choose the antonym of 'transparent'.","opaque",["clear","thin","bright"],"A transparent material lets light through; an opaque one does not."),
q("PJ",E,"Antonyms","m","Choose the antonym of 'temporary'.","permanent",["brief","sudden","partial"],"Temporary lasts for a limited time; permanent lasts indefinitely."),
q("J",E,"Antonyms","m","Choose the antonym of 'optimistic'.","pessimistic",["hopeful","cheerful","confident"],"An optimist expects good outcomes; a pessimist expects bad ones."),
q("J",E,"Antonyms","d","Choose the antonym of 'verbose'.","concise",["wordy","fluent","vague"],"Verbose writing uses too many words; concise writing uses few."),
q("JS",E,"Antonyms","d","Choose the antonym of 'benevolent'.","malevolent",["charitable","humble","cautious"],"Benevolent means wishing good for others; malevolent means wishing harm."),
q("JS",E,"Antonyms","d","Choose the antonym of 'amateur'.","professional",["beginner","novice","learner"],"An amateur does something for pleasure; a professional does it as an occupation."),
# ---- Vocabulary
q("PJ",E,"Vocabulary","e","A person who writes books is called a(n):","author",["editor","publisher","reader"],"An author is the writer of a book."),
q("P",E,"Vocabulary","e","A place where books are kept for borrowing is a:","library",["laboratory","stationery shop","museum"],"A library lends books to readers."),
q("P",E,"Vocabulary","e","What is the plural of 'child'?","children",["childs","childes","childrens"],"'Child' has an irregular plural: children."),
q("PJ",E,"Vocabulary","m","Which word is spelled correctly?","necessary",["neccessary","necesary","neccesary"],"Necessary has one c and two s's."),
q("PJ",E,"Vocabulary","m","Which word is spelled correctly?","separate",["seperate","seprate","separete"],"The correct spelling is s-e-p-a-r-a-t-e; the middle is 'para', not 'per'."),
q("J",E,"Vocabulary","m","Choose the correctly spelled word.","accommodation",["acommodation","accomodation","acommodasion"],"Accommodation has double c and double m."),
q("JS",E,"Vocabulary","d","Which word is spelled correctly?","occurrence",["occurence","ocurrence","occurance"],"Occurrence is spelled with double c and double r."),
q("JS",E,"Vocabulary","d","Which sentence uses 'affect' correctly?","The weather will affect our plans.",["The weather will have a large affect.","He tried to effect his friend's mood.","Her affect on us was a surprise."],"'Affect' is normally a verb meaning to influence; 'effect' is normally a noun meaning a result."),
q("J",E,"Vocabulary","d","In the sentence 'The principal's decision was irrevocable', 'irrevocable' means:","impossible to change",["open to debate","made in a hurry","kept secret"],"Irrevocable means that cannot be taken back or changed."),
# ---- One-word substitution
q("PJ",E,"One-Word Substitution","e","One who studies the stars:","astronomer",["astrologer","botanist","geologist"],"An astronomer studies stars and planets scientifically."),
q("PJ",E,"One-Word Substitution","e","A person who cannot read or write:","illiterate",["ignorant","innocent","invalid"],"Illiterate means unable to read or write."),
q("P",E,"One-Word Substitution","e","A doctor who treats children:","paediatrician",["surgeon","dentist","physician"],"A paediatrician is a children's doctor."),
q("PJ",E,"One-Word Substitution","m","A person who lives for a long time in a foreign land is a(n):","expatriate",["emigrant's child","tourist","traveller"],"An expatriate lives outside their home country."),
q("PJ",E,"One-Word Substitution","m","A speech made without preparation:","extempore",["monologue","sermon","lecture"],"An extempore speech is delivered without preparation."),
q("J",E,"One-Word Substitution","m","Government by the people is called:","democracy",["autocracy","aristocracy","monarchy"],"Democracy means rule by the people, usually through elected representatives."),
q("JS",E,"One-Word Substitution","d","A person who is present everywhere:","omnipresent",["omnipotent","omniscient","ominous"],"Omnipresent means present everywhere; omnipotent is all-powerful and omniscient is all-knowing."),
q("JS",E,"One-Word Substitution","d","A person who eats too much and is fond of food:","glutton",["gourmet","vegetarian","ascetic"],"A glutton eats and drinks to excess."),
# ---- Idioms
q("PJ",E,"Idioms","e","'A piece of cake' means:","something very easy",["a small dessert","a lucky gift","something expensive"],"The idiom describes a task that is very easy."),
q("PJ",E,"Idioms","e","'To break the ice' means:","to start a conversation in a friendly way",["to damage something","to feel very cold","to end a friendship"],"Breaking the ice means easing initial awkwardness between people."),
q("P",E,"Idioms","e","'Once in a blue moon' means:","very rarely",["every night","at midnight","very often"],"The phrase means something that happens only rarely."),
q("PJ",E,"Idioms","m","'To let the cat out of the bag' means:","to reveal a secret by mistake",["to free an animal","to make a big mistake in a shop","to lose one's temper"],"It means giving away a secret accidentally."),
q("PJ",E,"Idioms","m","'To beat around the bush' means:","to avoid coming to the point",["to hit a plant","to search carefully","to hurry up"],"The idiom means speaking indirectly instead of getting to the main issue."),
q("J",E,"Idioms","m","'The ball is in your court' means:","it is your turn to take action",["you are playing badly","you have won the game","the matter is over"],"It means the next move or decision is yours."),
q("JS",E,"Idioms","d","'To burn the midnight oil' means:","to study or work late into the night",["to waste fuel","to cause a fire","to wake up early"],"The idiom refers to working late, originally by lamp light."),
q("JS",E,"Idioms","d","'A blessing in disguise' means:","something good that seemed bad at first",["a hidden enemy","a religious gift","a false promise"],"It is an apparent misfortune that turns out to be beneficial."),
q("J",E,"Idioms","d","'To cry over spilt milk' means:","to regret something that cannot be undone",["to waste food","to behave like a child","to make a loud complaint"],"The proverb advises against grieving over a past loss that cannot be changed."),
]
