from helpers import q, qf
I = "Islamiat"
rows = [
q("PJ",I,"Quran","e","How many Surahs (chapters) are there in the Holy Quran?","114",["110","120","99"],"The Quran has 114 Surahs."),
q("PJ",I,"Quran","e","Which is the longest Surah of the Quran?","Al-Baqarah",["Al-Imran","An-Nisa","Al-Kahf"],"Surah Al-Baqarah has 286 verses and is the longest."),
q("P",I,"Quran","e","The first Surah of the Quran is:","Al-Fatiha",["Al-Baqarah","Al-Ikhlas","An-Nas"],"Al-Fatiha, the Opening, begins the Quran."),
q("PJ",I,"Quran","m","The shortest Surah of the Quran is:","Al-Kawthar",["Al-Ikhlas","Al-Asr","An-Nasr"],"Al-Kawthar has only three verses."),
q("PJ",I,"Quran","m","The first revelation to the Holy Prophet (PBUH) was the opening verses of Surah:","Al-Alaq",["Al-Muddaththir","Al-Fatiha","Al-Muzzammil"],"Iqra (Read) in Surah Al-Alaq was revealed first in the Cave of Hira."),
q("PJ",I,"Quran","m","Ayat-ul-Kursi is a verse of Surah:","Al-Baqarah",["Al-Imran","An-Nur","Yasin"],"It is verse 255 of Surah Al-Baqarah."),
q("J",I,"Quran","d","The Quran was revealed over a period of about:","23 years",["10 years","40 years","13 years only"],"The revelation lasted about 23 years, from the Makkan to the Madinan period."),
q("J",I,"Quran","d","Which Surah has no 'Bismillah' at its beginning?","At-Tawbah",["Al-Anfal","Al-Fatiha","An-Naml"],"Surah At-Tawbah (Bara'ah) begins without Bismillah; Surah An-Naml has it also within the verses."),
q("PJ",I,"Quran","m","The Quran was first compiled in book form during the caliphate of:","Hazrat Abu Bakr (RA)",["Hazrat Umar (RA)","Hazrat Ali (RA)","Hazrat Uthman (RA)"],"After the Battle of Yamama, Abu Bakr had the Quran collected into one volume; Uthman later standardised copies."),
q("J",I,"Quran","d","Standard copies (the Uthmani Mushaf) of the Quran were prepared and sent to major cities during the caliphate of:","Hazrat Uthman (RA)",["Hazrat Abu Bakr (RA)","Hazrat Umar (RA)","Hazrat Ali (RA)"],"Uthman standardised the text and dispatched copies to the main cities."),
q("PJ",I,"Hadith","e","The sayings of the Holy Prophet (PBUH) are called:","Hadith",["Fiqh","Tafsir","Seerah"],"Hadith are the recorded sayings, actions and approvals of the Prophet."),
q("PJ",I,"Hadith","m","Which compiler of Hadith wrote 'Sahih al-Bukhari'?","Imam Bukhari",["Imam Muslim","Imam Tirmidhi","Imam Abu Dawud"],"Imam Muhammad bin Ismail al-Bukhari compiled it."),
q("J",I,"Hadith","m","The collections of Hadith by Bukhari, Muslim, Tirmidhi, Abu Dawud, Nasai and Ibn Majah are called:","Sihah Sittah",["Kutub-e-Arba","Sab'a Mu'allaqat","Masanid"],"The 'six sound books' are known as Sihah Sittah."),
q("J",I,"Hadith","d","'Actions are judged by intentions' is the opening Hadith of:","Sahih al-Bukhari",["Muwatta Imam Malik","Sunan Ibn Majah","Musnad Ahmad"],"This Hadith on intentions is the first Hadith in Sahih al-Bukhari."),
q("PJ",I,"Hadith","m","According to a Hadith, 'cleanliness is':","half of faith",["a part of Hajj","the first duty","an optional virtue"],"The Prophet (PBUH) said cleanliness is half of faith."),
q("PJ",I,"Seerah","e","The Holy Prophet (PBUH) was born in the city of:","Makkah",["Madinah","Taif","Jerusalem"],"The Prophet was born in Makkah in the Year of the Elephant."),
q("PJ",I,"Seerah","e","The mother of the Holy Prophet (PBUH) was:","Hazrat Amina",["Hazrat Khadija","Hazrat Aisha","Hazrat Halima"],"His mother was Amina bint Wahb."),
q("P",I,"Seerah","e","The Holy Prophet (PBUH) migrated from Makkah to:","Madinah",["Taif","Jeddah","Damascus"],"The Hijra to Madinah took place in 622 CE."),
q("PJ",I,"Seerah","m","The Prophet (PBUH) was given the titles Sadiq and Amin for his:","truthfulness and trustworthiness",["bravery in battle","wealth and trade","poetry"],"The Quraysh called him the Truthful and the Trustworthy before prophethood."),
q("PJ",I,"Seerah","m","The Holy Prophet (PBUH) received the first revelation at the age of:","40",["25","30","63"],"The first revelation came when he was 40 years old."),
q("J",I,"Seerah","m","The first wife of the Holy Prophet (PBUH) was:","Hazrat Khadija (RA)",["Hazrat Aisha (RA)","Hazrat Hafsa (RA)","Hazrat Zainab (RA)"],"He married Khadija bint Khuwaylid before prophethood."),
q("J",I,"Seerah","d","The Treaty of Hudaybiyyah was signed in:","6 AH",["2 AH","8 AH","10 AH"],"The treaty was agreed with the Quraysh in the sixth year after Hijra."),
q("J",I,"Seerah","d","Makkah was conquered peacefully in:","8 AH",["6 AH","5 AH","10 AH"],"The conquest of Makkah took place in the eighth year of Hijra."),
q("PJ",I,"Prophets","e","Who was the first Prophet of Islam?","Hazrat Adam (AS)",["Hazrat Ibrahim (AS)","Hazrat Nuh (AS)","Hazrat Musa (AS)"],"Adam (AS) is the first Prophet."),
q("PJ",I,"Prophets","e","The last Prophet of Allah is:","Hazrat Muhammad (PBUH)",["Hazrat Isa (AS)","Hazrat Musa (AS)","Hazrat Ibrahim (AS)"],"Muhammad (PBUH) is the Seal of the Prophets."),
q("PJ",I,"Prophets","m","The Holy Book revealed to Hazrat Musa (AS) was the:","Torah (Taurat)",["Zabur","Injeel","Sahifas"],"The Torah was revealed to Musa; Zabur to Dawud; Injeel to Isa."),
q("PJ",I,"Prophets","m","Which Prophet is known as 'Khalilullah' (friend of Allah)?","Hazrat Ibrahim (AS)",["Hazrat Musa (AS)","Hazrat Yusuf (AS)","Hazrat Nuh (AS)"],"Ibrahim (AS) is called Khalilullah."),
q("J",I,"Islamic Personalities","m","Which Prophet built the Kaaba together with his son Ismail (AS)?","Hazrat Ibrahim (AS)",["Hazrat Adam (AS)","Hazrat Dawud (AS)","Hazrat Sulaiman (AS)"],"The Quran tells that Ibrahim and Ismail raised the foundations of the Kaaba."),
q("J",I,"Islamic Personalities","d","Which Prophet was swallowed by a large fish?","Hazrat Yunus (AS)",["Hazrat Ayyub (AS)","Hazrat Yaqub (AS)","Hazrat Ilyas (AS)"],"Yunus (AS) is the Prophet who was in the belly of the fish."),
q("PJ",I,"Pillars of Islam","e","How many pillars of Islam are there?","5",["4","6","7"],"The five are Shahada, Salah, Zakat, Sawm and Hajj."),
q("PJ",I,"Pillars of Islam","e","Fasting in the month of Ramadan is called:","Sawm",["Zakat","Hajj","Salah"],"Sawm is the fast from dawn to sunset."),
q("P",I,"Pillars of Islam","e","How many obligatory daily prayers are there?","5",["3","4","6"],"Fajr, Zuhr, Asr, Maghrib and Isha."),
q("PJ",I,"Pillars of Islam","m","The number of Fard rakats in the Zuhr prayer is:","4",["2","3","6"],"Zuhr has four Fard rakats."),
q("PJ",I,"Pillars of Islam","m","Zakat is generally due at the rate of:","2.5% of eligible savings",["10% of income","20% of savings","1% of income"],"The standard rate on eligible wealth held for a year is one-fortieth, i.e. 2.5%."),
q("PJ",I,"Pillars of Islam","m","Hajj is performed in the month of:","Dhul Hijjah",["Ramadan","Muharram","Rajab"],"Hajj takes place from the 8th to 13th of Dhul Hijjah."),
q("J",I,"Islamic Concepts","d","The night better than a thousand months, found in Ramadan, is:","Laylat al-Qadr",["Laylat al-Mi'raj","Shab-e-Barat","Laylat al-Isra"],"Surah Al-Qadr describes it as better than a thousand months."),
q("PJ",I,"Basic Beliefs","e","The belief in the Oneness of Allah is called:","Tawheed",["Risalat","Akhirah","Qadr"],"Tawheed is the central belief of Islam."),
q("PJ",I,"Basic Beliefs","m","The angel who brought revelation to the Prophets is:","Hazrat Jibreel (AS)",["Hazrat Mikail (AS)","Hazrat Israfil (AS)","Hazrat Azrael (AS)"],"Jibreel carried the revelation."),
q("PJ",I,"Basic Beliefs","m","The angel who will blow the Trumpet on the Day of Judgement is:","Hazrat Israfil (AS)",["Hazrat Jibreel (AS)","Hazrat Mikail (AS)","Hazrat Azrael (AS)"],"Israfil is the angel entrusted with the Trumpet."),
q("PJ",I,"Basic Beliefs","m","Belief in life after death is called:","Akhirah",["Risalat","Tawheed","Qiyas"],"Akhirah is the belief in the Hereafter."),
q("PJ",I,"Islamic Terminology","e","The Islamic term for the call to prayer is:","Adhan",["Iqamah","Khutbah","Takbir"],"Adhan is the call announced before each prayer."),
q("PJ",I,"Islamic Terminology","m","The Islamic term for a person who has memorised the whole Quran is:","Hafiz",["Qari","Mufti","Imam"],"A Hafiz knows the whole Quran by heart."),
q("J",I,"Islamic Concepts","d","The four main sources of Islamic law (in order) are the Quran, Sunnah, Ijma and:","Qiyas",["Ijtihad only","Urf only","Istishab only"],"Qiyas is analogical reasoning, the fourth source in the classical order."),
q("J",I,"Jurisprudence Basics","d","'Ijma' means:","consensus of the scholars",["analogy","personal opinion","custom"],"Ijma is agreement of qualified scholars on a ruling."),
q("J",I,"Jurisprudence Basics","d","The founder of the Hanafi school of fiqh is:","Imam Abu Hanifa",["Imam Malik","Imam Shafi'i","Imam Ahmad bin Hanbal"],"Imam Abu Hanifa (Nu'man bin Thabit) founded the Hanafi school."),
q("PJ",I,"Khulafa-e-Rashideen","e","Who was the first Caliph of Islam?","Hazrat Abu Bakr Siddiq (RA)",["Hazrat Umar (RA)","Hazrat Uthman (RA)","Hazrat Ali (RA)"],"Abu Bakr was the first of the Rightly Guided Caliphs."),
q("PJ",I,"Khulafa-e-Rashideen","m","Who was the second Caliph of Islam, known as 'Al-Farooq'?","Hazrat Umar (RA)",["Hazrat Abu Bakr (RA)","Hazrat Ali (RA)","Hazrat Uthman (RA)"],"Umar ibn al-Khattab was called Al-Farooq, the one who distinguishes truth from falsehood."),
q("PJ",I,"Khulafa-e-Rashideen","m","Which Caliph is known as 'Ghani' and 'Dhun-Nurayn'?","Hazrat Uthman (RA)",["Hazrat Ali (RA)","Hazrat Umar (RA)","Hazrat Abu Bakr (RA)"],"Uthman married two daughters of the Prophet (PBUH), hence Dhun-Nurayn."),
q("J",I,"Khulafa","d","The fourth Caliph of Islam was:","Hazrat Ali (RA)",["Hazrat Uthman (RA)","Hazrat Hasan (RA)","Hazrat Muawiya (RA)"],"Ali ibn Abi Talib was the fourth Rightly Guided Caliph."),
q("PJ",I,"Important Islamic Events","m","The first battle of Islam, fought in 2 AH, was the Battle of:","Badr",["Uhud","Khandaq","Hunain"],"Badr was fought on 17 Ramadan, 2 AH."),
q("J",I,"Battles and Events","m","The Battle of Uhud took place in:","3 AH",["2 AH","5 AH","7 AH"],"It was fought in Shawwal, 3 AH, near Madinah."),
q("J",I,"Battles and Events","d","The Battle of the Trench (Khandaq) was fought in:","5 AH",["3 AH","6 AH","8 AH"],"The defensive trench was dug around Madinah in 5 AH."),
q("PJ",I,"Islamic History","m","Sindh was conquered by Muhammad bin Qasim in:","712 CE",["622 CE","1186 CE","1526 CE"],"Muhammad bin Qasim defeated Raja Dahir in 712 CE; Sindh is called Bab-ul-Islam."),
q("J",I,"Islamic Civilization","m","Who wrote 'Al-Qanun fi al-Tibb' (The Canon of Medicine)?","Ibn Sina",["Al-Razi","Ibn Rushd","Al-Biruni"],"Ibn Sina (Avicenna) wrote the Canon, used for centuries as a medical text."),
q("J",I,"Islamic Civilization","d","The Muslim mathematician whose book gave algebra its name was:","Al-Khwarizmi",["Omar Khayyam","Ibn al-Haytham","Al-Kindi"],"Al-Khwarizmi's 'Al-Jabr' gave the word algebra."),
q("J",I,"Islamic Civilization","d","The capital of the Abbasid caliphate was:","Baghdad",["Damascus","Cairo","Cordoba"],"Al-Mansur founded Baghdad in 762 CE as the Abbasid capital; the Umayyads ruled from Damascus."),
q("PJ",I,"Islamic Ethics","e","Which of the following is a quality of a true Muslim according to Islam?","honesty",["lying","cheating","backbiting"],"Truthfulness is a basic Islamic virtue."),
q("PJ",I,"Islamic Ethics","m","Islam teaches that neighbours have:","rights over us",["no rights","rights only if they are Muslim","rights only if they are relatives"],"The Prophet (PBUH) stressed good treatment of neighbours regardless of faith."),
q("J",I,"Ethics and Social Principles","d","Which of the following is NOT permitted in Islamic business ethics?","charging interest (riba)",["honest trade","keeping contracts","fair weighing"],"Riba is prohibited in the Quran."),
]
