from helpers import q, qf
S, K, C, I, U = "Science", "Computer", "Social Studies", "Islamiat", "Urdu"
rows = [
# ---- Science (primary-level depth, some harder)
q("PJ",S,"Biology Basics","e","Which of these is a living thing?","a mango tree",["a stone","a table","a pencil"],"Living things grow, breathe, reproduce and respond to their surroundings."),
q("PJ",S,"Biology Basics","m","The study of living things is called:","biology",["geology","astronomy","chemistry"],"Biology is the science of life."),
q("PJ",S,"Biology Basics","d","Which of the following characteristics is shown ONLY by living things?","reproduction",["having mass","taking up space","being made of matter"],"All matter has mass and occupies space, but only living things reproduce."),
q("PJ",S,"Plants","m","Seeds are dispersed by wind in the case of:","dandelion",["coconut","mango","pea"],"Dandelion seeds have light, fluffy parts that the wind carries."),
q("PJ",S,"Plants","d","A plant kept in a dark room for several days turns pale because it cannot make:","chlorophyll",["roots","seeds","pollen"],"Chlorophyll formation needs light."),
q("PJ",S,"Plants","d","Which part of a plant mainly stores food in a carrot?","the root",["the leaf","the stem","the flower"],"A carrot is a swollen taproot that stores food."),
q("PJ",S,"Animals","m","Which animal breathes through gills?","fish",["whale","dolphin","crocodile"],"Fish take oxygen from water through gills; whales and dolphins are mammals that breathe air through lungs."),
q("PJ",S,"Animals","d","Which of the following is a pair of animals that both lay eggs?","hen and crocodile",["cow and goat","cat and dog","bat and whale"],"Birds and reptiles lay eggs; the other animals are mammals that give birth to live young."),
q("PJ",S,"Animals","d","Which animal hibernates (sleeps through the winter)?","bear",["camel","horse","sheep"],"Many bears sleep deeply through winter months."),
q("PJ",S,"Human Body","d","Which part of the eye controls the amount of light entering it?","pupil (through the iris)",["retina only","cornea only","eyelash"],"The iris changes the size of the pupil to control light."),
q("PJ",S,"Human Body","d","Which type of teeth are used for tearing food?","canines",["incisors","molars","wisdom teeth"],"Canines are pointed teeth that tear food; incisors cut and molars grind."),
q("PJ",S,"Human Body","m","Which organ filters waste from the blood and makes urine?","kidney",["liver","stomach","pancreas"],"The kidneys filter blood and form urine."),
q("PJ",S,"Human Body","e","How many chambers does the human heart have?","4",["2","3","5"],"Two atria and two ventricles."),
q("PJ",S,"Environment","d","Planting trees on a large scale helps to:","reduce carbon dioxide in the air",["increase floods","create smog","melt glaciers"],"Trees absorb carbon dioxide during photosynthesis."),
q("PJ",S,"Environment","d","Which of these is a non-renewable resource?","coal",["wind","sunlight","water power"],"Coal takes millions of years to form."),
q("PJ",S,"Environment","m","Acid rain is mainly caused by:","pollution from burning fuels",["clouds","wind","sunlight"],"Sulphur and nitrogen oxides from burning fuels form acids in rain."),
q("PJ",S,"Matter","d","Which of these is a physical change?","melting of wax",["burning of paper","rusting of iron","cooking of an egg"],"Melting changes state but forms no new substance."),
q("PJ",S,"Matter","d","Which gas do plants take in for photosynthesis?","carbon dioxide",["oxygen","nitrogen","hydrogen"],"Plants take in carbon dioxide and release oxygen."),
q("PJ",S,"Matter","m","What is the state of matter that has a fixed shape and a fixed volume?","solid",["liquid","gas","plasma"],"A solid keeps its own shape."),
q("PJ",S,"Matter","d","When salt is dissolved in water, the water is the:","solvent",["solute","solution","precipitate"],"The solvent is the substance that dissolves the solute."),
q("PJ",S,"Force and Motion","d","A force that opposes the motion of one surface over another is called:","friction",["gravity","magnetism","buoyancy"],"Friction acts against relative motion."),
q("PJ",S,"Force and Motion","m","A ball thrown upward comes back down because of:","gravity",["magnetism","friction","wind"],"Gravity pulls it back."),
q("PJ",S,"Force and Motion","d","A boat floats on water because of:","upthrust (buoyant force)",["magnetic force","friction","electric force"],"Water pushes up with a force equal to the weight of the displaced water."),
q("PJ",S,"Energy","d","Which energy conversion happens in a solar cell?","light to electrical energy",["heat to sound","chemical to light","mechanical to heat"],"A solar cell turns sunlight into electricity."),
q("PJ",S,"Energy","m","Food gives us:","chemical energy",["nuclear energy","sound energy","magnetic energy"],"Food stores chemical energy."),
q("PJ",S,"Heat","d","The metal handle of a pan feels hotter than a plastic one at the same temperature because metal is a better:","conductor of heat",["insulator","reflector","absorber of light"],"Metals conduct heat quickly, so heat flows into the hand faster."),
q("PJ",S,"Heat","m","Water in a pot heats up mainly by:","convection",["radiation only","conduction only","evaporation"],"Heated water rises and cooler water sinks, forming convection currents."),
q("PJ",S,"Heat","e","Which instrument measures body temperature?","clinical thermometer",["barometer","compass","voltmeter"],"A clinical thermometer is used for body temperature."),
q("PJ",S,"Light","d","Which colour of light is bent the most when white light passes through a prism?","violet",["red","green","yellow"],"Violet has the shortest wavelength and is refracted most."),
q("PJ",S,"Light","m","The Moon shines because it:","reflects sunlight",["produces its own light","burns gas","glows in the dark"],"The Moon is not luminous; it reflects the Sun's light."),
q("PJ",S,"Sound","d","Sound travels fastest in:","steel",["air","water","vacuum"],"Sound travels faster in solids than in liquids and gases."),
q("PJ",S,"Sound","m","The loudness of a sound depends on its:","amplitude",["colour","speed in vacuum","temperature only"],"A larger amplitude gives a louder sound."),
q("PJ",S,"Electricity","d","Which of these materials is an insulator?","rubber",["iron","copper","aluminium"],"Rubber does not allow current to pass."),
q("PJ",S,"Electricity","m","A device that is used to break or complete an electric circuit is a:","switch",["bulb","wire","battery"],"A switch opens or closes the circuit."),
q("PJ",S,"Earth and Space","d","Which layer of the Earth do we live on?","crust",["mantle","outer core","inner core"],"The crust is the thin outer layer."),
q("PJ",S,"Earth and Space","m","Day and night are caused by the Earth's:","rotation on its axis",["revolution around the Sun","tilt only","distance from the Moon"],"As the Earth spins, different parts face the Sun."),
q("PJ",S,"Earth and Space","d","Which planet is the closest to the Sun?","Mercury",["Venus","Earth","Mars"],"Mercury is the innermost planet."),
q("PJ",S,"Everyday Science","d","Why is a piece of iron coated with paint?","to prevent rusting",["to make it heavier","to make it conduct heat","to make it float"],"Paint keeps out air and moisture."),
q("PJ",S,"Everyday Science","m","Milk turns sour because of the action of:","bacteria",["light","wind","salt"],"Bacteria feed on milk sugar and produce lactic acid."),
q("PJ",S,"Everyday Science","e","A magnet attracts:","iron",["wood","plastic","glass"],"Iron is a magnetic material."),
q("PJ",S,"General Science","d","Which of these is a mixture that can be separated by filtration?","sand and water",["sugar and water","salt and water","alcohol and water"],"Sand does not dissolve, so filtration removes it."),
q("PJ",S,"General Science","m","The process of separating salt from sea water by heating is:","evaporation",["filtration","sublimation","condensation only"],"Water evaporates and leaves the salt behind."),
# ---- Computer (extra)
q("PJ",K,"Computer Fundamentals","m","Which of these is the correct sequence of the computer cycle?","input, process, output",["output, input, process","process, output, input","input, output, process"],"Data is entered, processed and then shown as output."),
q("PJ",K,"Computer Fundamentals","d","One kilobyte is equal to:","1024 bytes",["1000 bits","100 bytes","8 bytes"],"In computing, 1 KB = 1024 bytes."),
q("PJ",K,"Computer Fundamentals","d","Which of the following is the smallest unit of data?","bit",["byte","kilobyte","megabyte"],"A bit is a single binary digit, the smallest unit."),
q("PJ",K,"Hardware","m","The device that supplies power to the computer's components is the:","power supply unit",["monitor","mouse","scanner"],"The PSU converts mains power into the voltages the parts need."),
q("PJ",K,"Hardware","d","Which of these is both an input and an output device?","touch screen",["keyboard","printer","speaker"],"A touch screen takes input and shows output."),
q("PJ",K,"Software","d","A program that helps to protect a computer from viruses is called:","antivirus software",["a web browser","a word processor","a compiler"],"Antivirus programs find and remove malware."),
q("PJ",K,"Operating Systems","d","Which of the following is an example of an operating system for smartphones?","iOS",["Photoshop","Excel","Chrome"],"iOS runs on iPhones; Android is another."),
q("PJ",K,"Storage","d","Which storage device has no moving parts?","solid-state drive (SSD)",["hard disk drive","floppy disk","CD-ROM"],"An SSD stores data in flash memory chips."),
q("PJ",K,"Storage","m","A CD-ROM stores data that:","can only be read",["is erased when power is off","can be changed freely","is stored in RAM"],"ROM stands for read-only memory."),
q("PJ",K,"Internet","d","What does the 'www' in a website address stand for?","World Wide Web",["World Window Web","Wide Web World","Web Wide World"],"It names the system of linked web pages."),
q("PJ",K,"Internet","m","An email attachment is:","a file sent along with an email",["the subject of an email","a type of virus","an address"],"Attachments can be documents, pictures or other files."),
q("PJ",K,"Networking Basics","d","Wi-Fi is used to connect devices:","without cables",["only with a telephone line","only with fibre","only with a printer cable"],"Wi-Fi is a wireless networking technology."),
q("PJ",K,"MS Office","d","Which button is used in MS Word to make selected text darker (bold)?","B",["I","U","A"],"B = bold, I = italic, U = underline."),
q("PJ",K,"MS Office","m","Which shortcut key saves a document?","Ctrl + S",["Ctrl + P","Ctrl + N","Ctrl + A"],"Ctrl+S saves; Ctrl+P prints."),
q("PJ",K,"Digital Literacy","m","Which of the following is a safe online habit?","not sharing your password",["accepting every friend request","clicking unknown links","using one password everywhere"],"A password should be kept private."),
q("PJ",K,"Cybersecurity Awareness","d","Two-factor authentication means:","using two different proofs of identity to log in",["using two computers","using two passwords for different sites","logging in twice"],"For example a password plus a code sent to a phone."),
# ---- Social Studies (extra)
q("PJ",C,"History","m","The Indus Valley Civilisation had its famous cities at Mohenjo-daro and:","Harappa",["Babylon","Memphis","Athens"],"Harappa (in Punjab) and Mohenjo-daro (in Sindh) were its major cities."),
q("PJ",C,"History","d","The Mughal emperor who built the Badshahi Mosque in Lahore was:","Aurangzeb Alamgir",["Akbar","Shah Jahan","Babur"],"Aurangzeb built the mosque, completed in 1673."),
q("PJ",C,"History","d","The 1965 war between Pakistan and India began in the month of:","September",["March","December","January"],"The war began in September 1965; Defence Day is on 6 September."),
q("PJ",C,"History","m","Who is known as the 'Conqueror of Sindh' in the year 712 CE?","Muhammad bin Qasim",["Tariq bin Ziyad","Mahmud of Ghazni","Salahuddin Ayyubi"],"Muhammad bin Qasim entered Sindh in 711-712 CE."),
q("PJ",C,"Provinces","d","Which province of Pakistan borders both Iran and Afghanistan?","Balochistan",["Sindh","Punjab","Khyber Pakhtunkhwa"],"Balochistan has borders with both Iran and Afghanistan."),
q("PJ",C,"Provinces","m","Which province of Pakistan borders India as well as the Arabian Sea?","Sindh",["Punjab","Balochistan","Khyber Pakhtunkhwa"],"Sindh has a coast on the Arabian Sea and an eastern border with India."),
q("PJ",C,"Pakistan Geography","d","The Cholistan Desert is located mainly in:","Punjab",["Sindh","Balochistan","Gilgit-Baltistan"],"Cholistan lies in southern Punjab near Bahawalpur."),
q("PJ",C,"Pakistan Geography","m","Which is the highest peak of Pakistan?","K2",["Nanga Parbat","Tirich Mir","Rakaposhi"],"K2 is the highest at 8,611 m."),
q("PJ",C,"Pakistan Geography","m","Which river forms the main water supply of Sindh?","Indus",["Jhelum","Ravi","Sutlej"],"Sindh depends on the Indus and its barrages and canals."),
q("PJ",C,"National Symbols","d","The national tree of Pakistan is:","deodar",["neem","banyan","mango"],"The deodar cedar is the national tree."),
q("PJ",C,"National Symbols","d","The national bird of Pakistan is the:","chukar",["sparrow","peacock","crow"],"The chukar partridge is the national bird."),
q("PJ",C,"Constitution and Civics","d","Who elects the Prime Minister of Pakistan?","the National Assembly",["the Senate","the Supreme Court","the Chief Minister"],"The Prime Minister is elected by the members of the National Assembly."),
q("PJ",C,"Culture","d","Which Sindhi musical instrument is a type of flute?","Bansuri",["Sarangi","Dhol","Tabla"],"The bansuri is a bamboo flute used in Sindhi folk music."),
# ---- Islamiat (extra harder)
q("PJ",I,"Quran","d","The Surah in which the story of Hazrat Yusuf (AS) is told is Surah:","Yusuf",["Al-Kahf","Maryam","An-Naml"],"Surah Yusuf (12) tells his story in full."),
q("PJ",I,"Seerah","d","The Prophet (PBUH) was raised after the death of his grandfather by his uncle:","Abu Talib",["Abu Lahab","Hamza","Abbas"],"After Abdul Muttalib died, Abu Talib cared for him."),
q("PJ",I,"Seerah","d","In which cave did the Prophet (PBUH) and Hazrat Abu Bakr (RA) hide during the Hijra?","Cave Thawr",["Cave Hira","Cave Uhud","Cave Badr"],"They hid in Cave Thawr for three days."),
q("PJ",I,"Prophets","d","The Prophet who could speak with birds and ruled a great kingdom was:","Hazrat Sulaiman (AS)",["Hazrat Ayyub (AS)","Hazrat Yaqub (AS)","Hazrat Idris (AS)"],"The Quran mentions Sulaiman (AS) and the speech of birds."),
q("PJ",I,"Pillars of Islam","d","The Kalima 'Shahada' is the declaration of:","faith in Allah and His Messenger",["fasting","charity","the pilgrimage"],"It declares that there is no god but Allah and Muhammad is His Messenger."),
q("PJ",I,"Basic Beliefs","d","How many Heavenly Books are named in the Quran as revealed to different Prophets (Torah, Zabur, Injeel and the Quran)?","4",["3","5","6"],"The four named books are Torah, Zabur, Injeel and the Quran.",chk=4),
q("PJ",I,"Khulafa-e-Rashideen","d","The Caliph who sent the army to Syria and Iraq and organised the first public administration was:","Hazrat Umar (RA)",["Hazrat Abu Bakr (RA)","Hazrat Ali (RA)","Hazrat Uthman (RA)"],"Umar expanded the state and set up administrative departments."),
q("PJ",I,"Islamic Ethics","d","Which of the following is a duty towards parents in Islam?","to obey and respect them in all that is good",["to ignore their advice","to avoid them","to be rude when they are old"],"The Quran commands kindness and respect to parents."),
# ---- Urdu (harder, PST level)
q("PJ",U,"Idioms","d","محاورہ 'سر پر سوار ہونا' کا مطلب کیا ہے؟","پیچھے پڑ جانا",["گھوڑے پر چڑھنا","سر درد ہونا","خوش ہونا"],"اس محاورے کا مطلب ہے کسی کے پیچھے پڑ جانا۔"),
q("PJ",U,"Idioms","d","محاورہ 'پاپڑ بیلنا' کا مطلب کیا ہے؟","بہت مشقت کرنا",["کھانا پکانا","آسانی سے کام ہونا","سیر کو جانا"],"اس محاورے کا مطلب ہے بہت مشکل اٹھانا۔"),
q("PJ",U,"Synonyms","d","'مفلس' کا مترادف کیا ہے؟","نادار",["دولت مند","سخی","امیر"],"'مفلس' اور 'نادار' دونوں کا مطلب غریب ہے۔"),
q("PJ",U,"Synonyms","d","'تیز' کا مترادف کیا ہے؟","سریع",["سست","دھیما","نرم"],"'سریع' کا مطلب تیز ہے۔"),
q("PJ",U,"Antonyms","d","'اتحاد' کا متضاد کیا ہے؟","انتشار",["یکجہتی","میل","بھائی چارہ"],"'اتحاد' کا الٹ 'انتشار' ہے۔"),
q("PJ",U,"Antonyms","d","'ظلم' کا متضاد کیا ہے؟","انصاف",["جبر","ستم","نا انصافی"],"'ظلم' کا الٹ 'انصاف' ہے۔"),
q("PJ",U,"Singular and Plural","d","'حاکم' کی جمع کیا ہے؟","حکام",["حاکمیں","حاکمات","حاکمے"],"'حاکم' کی جمع 'حکام' ہے۔"),
q("PJ",U,"Singular and Plural","d","'تاجر' کی جمع کیا ہے؟","تجار",["تاجریں","تاجرات","تاجرے"],"'تاجر' کی جمع 'تجار' ہے۔"),
q("PJ",U,"Meaning","d","'ایثار' کا مطلب کیا ہے؟","دوسروں کے لیے اپنا فائدہ چھوڑ دینا",["لالچ","غصہ","ڈر"],"'ایثار' کا مطلب ہے دوسروں کو اپنے اوپر ترجیح دینا۔"),
q("PJ",U,"Meaning","d","'خلوص' کا مطلب کیا ہے؟","سچے دل سے محبت",["دکھاوا","ناراضی","تجارت"],"'خلوص' کا مطلب ہے بناوٹ کے بغیر سچائی اور پاکیزگی۔"),
q("PJ",U,"Grammar","d","'کتاب میز پر رکھی ہے' میں 'پر' کیا ہے؟","حرفِ جار",["حرفِ عطف","اسم","صفت"],"'پر' اسم 'میز' کا تعلق فعل سے ظاہر کرتا ہے، اس لیے حرفِ جار ہے۔"),
]
