from helpers import q, qf
S = "Science"
rows = [
# ---- Physics extra
q("S",S,"Physics: Mechanics","e","Which of these is a scalar quantity?","mass",["velocity","force","displacement"],"Mass has magnitude only; the others have direction too."),
q("S",S,"Physics: Mechanics","e","The SI unit of work is the:","joule",["watt","newton","pascal"],"Work = force x distance, measured in joules."),
q("S",S,"Physics: Mechanics","m","A force of 10 N moves an object 3 m in its own direction. The work done is:","30 J",["13 J","3.3 J","7 J"],"W = Fd = 10 x 3 = 30 J.",chk="30 J"),
q("S",S,"Physics: Mechanics","m","The acceleration due to gravity near the Earth's surface is about:","9.8 m/s squared",["98 m/s squared","0.98 m/s squared","6.7 m/s squared"],"g is about 9.8 m/s squared."),
q("S",S,"Physics: Mechanics","d","A lift of mass 500 kg is raised at constant speed. The tension in the cable (g = 10 m/s squared) is:","5,000 N",["500 N","50 N","10,000 N"],"At constant speed the net force is zero, so tension = weight = 500 x 10 = 5,000 N.",chk="{:,} N".format(500*10)),
q("S",S,"Physics: Heat and Thermodynamics","m","Heat flows from a body at a higher temperature to one at a lower temperature until they reach:","thermal equilibrium",["absolute zero","the melting point","the critical point"],"At thermal equilibrium there is no net heat flow."),
q("S",S,"Physics: Heat and Thermodynamics","d","The efficiency of a heat engine that takes in 500 J of heat and does 150 J of work is:","30%",["70%","15%","33%"],"Efficiency = 150/500 = 30%.",chk="30%"),
q("S",S,"Physics: Light and Optics","m","A ray of light strikes a plane mirror at 30 degrees to the normal. The angle of reflection is:","30 degrees",["60 degrees","90 degrees","0 degrees"],"The angle of reflection equals the angle of incidence."),
q("S",S,"Physics: Light and Optics","d","The colour of light with the longest wavelength in the visible spectrum is:","red",["violet","green","blue"],"Red has the longest visible wavelength and violet the shortest."),
q("S",S,"Physics: Sound and Waves","m","The speed of sound in air at room temperature is about:","340 m/s",["3,400 m/s","34 m/s","3 x 10 to the power 8 m/s"],"Sound travels at roughly 340 m/s in air."),
q("S",S,"Physics: Electricity and Magnetism","e","Like poles of two magnets:","repel each other",["attract each other","have no effect","exchange poles"],"North repels north and south repels south."),
q("S",S,"Physics: Electricity and Magnetism","m","Two 4 ohm resistors are connected in series. The total resistance is:","8 ohms",["2 ohms","4 ohms","16 ohms"],"In series, resistances add: 4 + 4 = 8 ohms.",chk="8 ohms"),
q("S",S,"Physics: Electricity and Magnetism","d","The SI unit of electric charge is the:","coulomb",["ampere","volt","farad"],"Charge is measured in coulombs; 1 A = 1 C per second."),
q("S",S,"Physics: Modern Physics","e","Which particle has a negative charge?","electron",["proton","neutron","alpha nucleus"],"Electrons carry a negative charge."),
# ---- Chemistry extra
q("S",S,"Chemistry: Atomic Structure","e","Which particle in an atom has no electric charge?","neutron",["proton","electron","nucleus"],"Neutrons are neutral."),
q("S",S,"Chemistry: Atomic Structure","m","The maximum number of electrons in the first shell of an atom is:","2",["8","18","6"],"The K shell holds at most 2 electrons."),
q("S",S,"Chemistry: Periodic Table","m","The modern periodic table arranges elements in order of increasing:","atomic number",["atomic mass","density","melting point"],"The modern periodic law is based on atomic number."),
q("S",S,"Chemistry: Periodic Table","m","Which of these is a halogen?","chlorine",["sodium","neon","magnesium"],"The halogens are fluorine, chlorine, bromine, iodine and astatine (Group 17)."),
q("S",S,"Chemistry: Chemical Bonding","m","Which compound has ionic bonds?","magnesium oxide",["methane","carbon dioxide","water"],"Magnesium oxide forms from Mg2+ and O2- ions."),
q("S",S,"Chemistry: Reactions and Stoichiometry","e","The chemical formula of carbon dioxide is:","CO2",["CO","C2O","CO3"],"One carbon atom and two oxygen atoms."),
q("S",S,"Chemistry: Reactions and Stoichiometry","m","How many atoms are present in one molecule of H2SO4?","7",["4","6","3"],"2 hydrogen + 1 sulphur + 4 oxygen = 7 atoms.",chk=7),
q("S",S,"Chemistry: Reactions and Stoichiometry","m","The molar mass of water (H = 1, O = 16) is:","18 g/mol",["17 g/mol","16 g/mol","34 g/mol"],"2 x 1 + 16 = 18 g/mol.",chk="18 g/mol"),
q("S",S,"Chemistry: Reactions and Stoichiometry","d","A catalyst:","speeds up a reaction without being used up",["is used up in the reaction","slows a reaction down","changes the products formed"],"A catalyst provides an easier route and is regenerated."),
q("S",S,"Chemistry: Acids, Bases and Salts","e","Which of these is a strong acid?","hydrochloric acid",["acetic acid","carbonic acid","citric acid"],"Hydrochloric acid ionises completely in water."),
q("S",S,"Chemistry: Acids, Bases and Salts","m","Milk of magnesia, used to treat acidity, is a:","base",["acid","salt only","neutral oxide"],"It neutralises excess stomach acid."),
q("S",S,"Chemistry: Acids, Bases and Salts","m","Sodium hydroxide solution turns red litmus:","blue",["red","green","colourless"],"Bases turn red litmus blue."),
q("S",S,"Chemistry: Organic Basics","m","The molecular formula of ethane is:","C2H6",["C2H4","C2H2","CH4"],"Ethane is an alkane with two carbons: CnH(2n+2) gives C2H6."),
q("S",S,"Chemistry: Organic Basics","d","The gas ripening fruit and used to make polythene is:","ethene",["methane","ethane","propane"],"Ethene (ethylene) is the alkene used for polythene and acts as a ripening hormone."),
q("S",S,"Chemistry: States of Matter","m","The temperature at which a solid melts to a liquid is called its:","melting point",["boiling point","freezing point only","sublimation point"],"The melting point is the temperature of solid-liquid change."),
q("S",S,"Chemistry: States of Matter","m","Particles in a gas:","move randomly with large spaces between them",["are tightly packed","vibrate in fixed positions","form a regular lattice"],"Gas particles are far apart and move freely."),
q("S",S,"Chemistry: Atomic Structure","d","Which scientist proposed the nuclear model of the atom after the gold-foil experiment?","Ernest Rutherford",["J. J. Thomson","John Dalton","Niels Bohr"],"Rutherford's alpha-scattering experiment revealed a small dense nucleus."),
# ---- Biology extra
q("S",S,"Biology: Cell Biology","e","The part of the cell that controls its activities is the:","nucleus",["vacuole","cell wall","cytoplasm"],"The nucleus directs the cell's functions."),
q("S",S,"Biology: Cell Biology","m","Which organelle is found only in plant cells and carries out photosynthesis?","chloroplast",["mitochondrion","ribosome","lysosome"],"Chloroplasts contain chlorophyll."),
q("S",S,"Biology: Cell Biology","m","The jelly-like fluid inside a cell in which organelles float is the:","cytoplasm",["nucleolus","cell membrane","cell wall"],"The cytoplasm holds the organelles."),
q("S",S,"Biology: Human Physiology","e","The pigment that gives blood its red colour is:","haemoglobin",["chlorophyll","melanin","keratin"],"Haemoglobin carries oxygen and is red."),
q("S",S,"Biology: Human Physiology","m","The largest gland in the human body is the:","liver",["pancreas","thyroid","pituitary"],"The liver is the largest gland and also the largest internal organ."),
q("S",S,"Biology: Human Physiology","m","Which part of the nervous system consists of the brain and the spinal cord?","central nervous system",["peripheral nervous system","autonomic system only","sympathetic system only"],"The brain and spinal cord form the CNS."),
q("S",S,"Biology: Human Physiology","d","The hormone that lowers blood sugar is:","insulin",["glucagon","adrenaline","thyroxine"],"Insulin helps cells absorb glucose; glucagon raises blood sugar."),
q("S",S,"Biology: Human Physiology","d","White blood cells mainly help the body to:","fight infection",["carry oxygen","clot blood","carry digested food"],"They are part of the immune system."),
q("S",S,"Biology: Human Physiology","e","The normal number of chambers in the human heart is:","four",["two","three","five"],"The heart has two atria and two ventricles."),
q("S",S,"Biology: Plant Biology","e","The process by which a seed grows into a seedling is called:","germination",["pollination","fertilisation","respiration"],"Germination begins when a seed gets water, warmth and air."),
q("S",S,"Biology: Plant Biology","m","Which part of the flower becomes the seed after fertilisation?","ovule",["anther","stigma","petal"],"The fertilised ovule develops into the seed."),
q("S",S,"Biology: Plant Biology","m","The loss of water vapour from the aerial parts of a plant is:","transpiration",["translocation","respiration","guttation only"],"Most of it occurs through the stomata."),
q("S",S,"Biology: Plant Biology","d","Plants that complete their life cycle in two years are called:","biennials",["annuals","perennials","ephemerals"],"Biennials grow in the first year and flower in the second."),
q("S",S,"Biology: Genetics and Evolution","m","The basic unit of heredity is the:","gene",["cell","tissue","organ"],"Genes are segments of DNA that carry hereditary information."),
q("S",S,"Biology: Genetics and Evolution","d","A person with the blood group AB has the genotype:","IAIB",["IAIA","ii","IBi"],"AB is produced by one IA and one IB allele (codominance)."),
q("S",S,"Biology: Genetics and Evolution","m","Which sex chromosomes does a human female have?","XX",["XY","XO","YY"],"Females have two X chromosomes and males have XY."),
q("S",S,"Biology: Ecology and Environment","m","The place where an organism lives is called its:","habitat",["niche","population","community"],"The habitat is the organism's home."),
q("S",S,"Biology: Ecology and Environment","m","Which of these is an abiotic factor of an ecosystem?","temperature",["bacteria","grass","insects"],"Abiotic factors are non-living, such as temperature, light and water."),
q("S",S,"Biology: Ecology and Environment","d","The variety of living things in an area is called:","biodiversity",["biomass","population density","succession"],"Biodiversity includes species, genetic and ecosystem variety."),
q("S",S,"Biology: Microorganisms and Health","m","Which of these is a vaccine-preventable disease?","polio",["diabetes","cancer","asthma"],"Polio is prevented by vaccination."),
q("S",S,"Biology: Microorganisms and Health","m","The bacterium that causes tuberculosis is:","Mycobacterium tuberculosis",["Vibrio cholerae","Salmonella typhi","Plasmodium"],"Vibrio causes cholera, Salmonella typhi causes typhoid, and Plasmodium (a protozoan) causes malaria."),
q("S",S,"Biology: Microorganisms and Health","d","Yeast is used in baking and brewing because it carries out:","fermentation",["photosynthesis","nitrogen fixation","osmosis only"],"Yeast produces carbon dioxide and alcohol by fermenting sugars."),
q("S",S,"Biology: Microorganisms and Health","e","Which of these diseases is spread through contaminated water?","cholera",["measles","rabies","tetanus"],"Cholera spreads through water contaminated with the bacterium."),
]
