from helpers import q, qf
S = "Science"
rows = [
# ---- Biology basics, Human body
q("PJ",S,"Human Body","e","Which organ pumps blood around the human body?","heart",["lungs","liver","kidney"],"The heart is a muscular pump that circulates blood."),
q("PJ",S,"Human Body","e","How many bones does an adult human body have?","206",["106","306","260"],"An adult human skeleton has 206 bones."),
q("P",S,"Human Body","e","Which sense organ is responsible for the sense of smell?","nose",["tongue","ear","skin"],"Smell receptors are located in the nose."),
q("PJ",S,"Human Body","m","Which blood cells carry oxygen?","red blood cells",["white blood cells","platelets","plasma"],"Haemoglobin in red blood cells binds oxygen."),
q("PJ",S,"Human Body","m","Where does most digestion of food and absorption of nutrients take place?","small intestine",["stomach","large intestine","oesophagus"],"The small intestine is long and lined with villi, where digestion is completed and nutrients are absorbed."),
q("PJ",S,"Human Body","m","Which vitamin is made in the skin when it is exposed to sunlight?","vitamin D",["vitamin A","vitamin C","vitamin K"],"Sunlight lets the skin produce vitamin D."),
q("J",S,"Human Body","d","Which part of the brain controls balance and coordination of movement?","cerebellum",["cerebrum","medulla oblongata","hypothalamus"],"The cerebellum coordinates movement and balance."),
q("J",S,"Human Body","d","The functional unit of the kidney is the:","nephron",["neuron","alveolus","villus"],"Each kidney contains about a million nephrons which filter the blood."),
q("PJ",S,"Human Body","m","Which gas do we breathe out in larger amounts than we breathe in?","carbon dioxide",["oxygen","nitrogen","hydrogen"],"Respiration releases carbon dioxide, so exhaled air has more of it than inhaled air."),
q("P",S,"Human Body","e","Which of these is the largest organ of the human body?","skin",["liver","brain","heart"],"The skin covers the whole body and is the largest organ."),
q("PJ",S,"Human Body","m","Deficiency of vitamin C causes:","scurvy",["rickets","night blindness","beriberi"],"Lack of vitamin C causes scurvy; rickets is a lack of D, night blindness of A, and beriberi of B1."),
q("PJ",S,"Human Body","m","The normal human body temperature is about:","37 degrees Celsius",["25 degrees Celsius","42 degrees Celsius","30 degrees Celsius"],"Normal body temperature is about 37 degrees Celsius (98.6 degrees Fahrenheit)."),
# ---- Plants
q("PJ",S,"Plants","e","The process by which plants make their own food using sunlight is called:","photosynthesis",["respiration","transpiration","digestion"],"Photosynthesis uses light, carbon dioxide and water to make glucose."),
q("PJ",S,"Plants","e","Which part of a plant absorbs water from the soil?","roots",["leaves","flowers","stem"],"Roots absorb water and minerals."),
q("P",S,"Plants","e","Which part of a flower develops into the fruit?","ovary",["petal","sepal","anther"],"After fertilisation the ovary becomes the fruit."),
q("PJ",S,"Plants","m","Which green pigment in leaves traps sunlight?","chlorophyll",["carotene","xanthophyll","melanin"],"Chlorophyll absorbs light energy for photosynthesis."),
q("PJ",S,"Plants","m","Loss of water vapour from the leaves of a plant is called:","transpiration",["germination","pollination","fertilisation"],"Transpiration is evaporation of water mainly through stomata."),
q("J",S,"Plants","d","Which tissue carries water and minerals upward from the roots?","xylem",["phloem","cortex","epidermis"],"Xylem carries water up; phloem carries food made in the leaves."),
q("PJ",S,"Plants","m","The transfer of pollen from an anther to a stigma is called:","pollination",["germination","fertilisation","transpiration"],"Pollination is the movement of pollen to a stigma; fertilisation comes later."),
q("J",S,"Plants","d","Which gas is released as a by-product of photosynthesis?","oxygen",["carbon dioxide","nitrogen","methane"],"Water is split during photosynthesis and oxygen is released."),
# ---- Animals
q("PJ",S,"Animals","e","Which animal is a mammal?","bat",["frog","snake","eagle"],"Bats are the only mammals able to fly; they feed their young with milk."),
q("P",S,"Animals","e","Which of these animals lays eggs?","hen",["cow","goat","cat"],"A hen is a bird and lays eggs; the others give birth to live young."),
q("PJ",S,"Animals","m","The life cycle of a butterfly is: egg, ___, pupa, adult.","larva",["nymph","embryo","seed"],"A butterfly undergoes complete metamorphosis: egg, larva (caterpillar), pupa, adult."),
q("PJ",S,"Animals","m","Animals that eat both plants and animals are called:","omnivores",["herbivores","carnivores","decomposers"],"Omnivores eat both."),
q("P",S,"Animals","e","How many legs does an insect have?","6",["4","8","10"],"All adult insects have six legs."),
q("J",S,"Animals","d","Which of these animals is a cold-blooded vertebrate?","lizard",["whale","sparrow","rabbit"],"Reptiles such as lizards are cold-blooded vertebrates; whales and rabbits are mammals and sparrows are birds."),
# ---- Cells & general biology (JEST)
q("J",S,"Cells","m","Which part of the cell contains the genetic material?","nucleus",["cytoplasm","cell membrane","vacuole"],"The nucleus holds the DNA of an animal or plant cell."),
q("J",S,"Cells","m","The 'powerhouse of the cell' is the:","mitochondrion",["ribosome","nucleus","chloroplast"],"Mitochondria release energy from food during respiration."),
q("J",S,"Cells","d","Which structure is found in plant cells but NOT in animal cells?","cell wall",["cell membrane","nucleus","mitochondria"],"Plant cells have a cellulose cell wall; animal cells do not."),
q("J",S,"Cells","d","Which organelle is the site of protein synthesis?","ribosome",["lysosome","Golgi body","vacuole"],"Ribosomes assemble amino acids into proteins."),
q("J",S,"Biology","d","The scientist who first observed cells in a thin slice of cork was:","Robert Hooke",["Louis Pasteur","Gregor Mendel","Charles Darwin"],"Robert Hooke described cells in cork in 1665."),
# ---- Environment / Ecology
q("PJ",S,"Environment","e","Which of the following is a renewable source of energy?","sunlight",["coal","petroleum","natural gas"],"Sunlight is continuously replenished; fossil fuels are not."),
q("P",S,"Environment","e","Which gas is mainly responsible for global warming?","carbon dioxide",["oxygen","helium","argon"],"Carbon dioxide is the main greenhouse gas added by human activity."),
q("PJ",S,"Environment","m","The layer of the atmosphere that protects us from harmful ultraviolet rays is the:","ozone layer",["troposphere","ionosphere","exosphere"],"Ozone absorbs most of the Sun's harmful ultraviolet radiation."),
q("PJ",S,"Environment","m","Which of these is a decomposer?","fungi",["grass","grasshopper","frog"],"Fungi break down dead organisms and recycle nutrients."),
q("J",S,"Ecology","m","In a food chain 'grass -> grasshopper -> frog -> snake', the frog is a:","secondary consumer",["producer","primary consumer","decomposer"],"The grasshopper is the primary consumer, so the frog that eats it is the secondary consumer."),
q("J",S,"Ecology","d","The removal of forests on a large scale is called:","deforestation",["afforestation","reforestation","desertification"],"Deforestation is the clearing of forests; afforestation is planting them."),
q("J",S,"Ecology","d","Which of these best describes a food web?","interconnected food chains",["a single food chain","a list of producers","a pyramid of energy only"],"A food web shows how many food chains in an ecosystem overlap."),
# ---- Matter / Chemistry
q("PJ",S,"Matter","e","Water changes into steam at:","100 degrees Celsius",["0 degrees Celsius","50 degrees Celsius","212 degrees Celsius"],"Water boils at 100 degrees Celsius at sea level (212 is the same temperature in Fahrenheit)."),
q("P",S,"Matter","e","Which of these is a solid at room temperature?","iron",["mercury","oxygen","water"],"Iron is a solid; mercury is a liquid; oxygen is a gas."),
q("PJ",S,"Matter","m","The process of a gas changing directly into a liquid is called:","condensation",["evaporation","sublimation","melting"],"Water vapour condenses into droplets when cooled."),
q("PJ",S,"Matter","m","Which of these is a mixture?","air",["water","oxygen","gold"],"Air is a mixture of nitrogen, oxygen and other gases; the others are pure substances."),
q("J",S,"Matter","m","What is the chemical symbol for sodium?","Na",["S","So","N"],"Sodium's symbol is Na, from its Latin name natrium."),
q("J",S,"Chemistry","m","The chemical formula of table salt is:","NaCl",["KCl","NaOH","HCl"],"Table salt is sodium chloride, NaCl."),
q("J",S,"Chemistry","d","The pH of a neutral solution at room temperature is:","7",["0","10","14"],"pH 7 is neutral; below 7 is acidic and above 7 is basic."),
q("J",S,"Chemistry","d","Which gas is produced when zinc reacts with dilute hydrochloric acid?","hydrogen",["oxygen","carbon dioxide","chlorine"],"Metal + acid gives a salt and hydrogen: zinc chloride and hydrogen."),
q("J",S,"Chemical Reactions","d","Rusting of iron is an example of:","oxidation",["reduction only","evaporation","sublimation"],"Iron combines with oxygen and water to form hydrated iron oxide (rust)."),
q("J",S,"Chemical Reactions","m","Which of these is a chemical change?","burning of wood",["melting of ice","dissolving sugar in water","breaking glass"],"Burning produces new substances, so it is a chemical change."),
q("J",S,"Chemistry","d","The most abundant gas in the Earth's atmosphere is:","nitrogen",["oxygen","carbon dioxide","argon"],"Nitrogen makes up about 78% of dry air; oxygen about 21%."),
# ---- Force, motion, energy, heat, light, sound, electricity
q("PJ",S,"Force and Motion","e","The force that pulls objects towards the centre of the Earth is called:","gravity",["friction","magnetism","tension"],"Gravity attracts objects toward the Earth."),
q("PJ",S,"Force and Motion","m","The SI unit of force is the:","newton",["joule","watt","pascal"],"Force is measured in newtons."),
q("J",S,"Force","m","Which of these reduces friction?","lubricating oil",["a rough surface","sand","a rubber sole"],"Oil forms a thin film between surfaces and reduces friction."),
q("J",S,"Motion","d","A car moves 100 m in 5 s at constant speed. Its speed is:","20 m/s",["500 m/s","0.05 m/s","95 m/s"],"Speed = distance / time = 100/5 = 20 m/s.",chk="20 m/s"),
q("J",S,"Force","d","According to Newton's first law, an object at rest stays at rest unless:","an unbalanced force acts on it",["it is very heavy","it has no mass","gravity is absent"],"Newton's first law (inertia): the state of motion changes only when a net force acts."),
q("J",S,"Motion","d","The slope of a distance-time graph gives:","speed",["acceleration","force","mass"],"Change in distance divided by change in time is speed."),
q("PJ",S,"Energy","e","The energy stored in a stretched rubber band is:","potential energy",["kinetic energy","sound energy","nuclear energy"],"Stretching stores elastic potential energy."),
q("PJ",S,"Energy","m","In a falling object, potential energy is converted mainly into:","kinetic energy",["chemical energy","sound only","light energy"],"As height decreases, gravitational potential energy becomes kinetic energy."),
q("J",S,"Energy","d","The SI unit of energy is the:","joule",["watt","newton","volt"],"Energy and work are measured in joules; the watt is the unit of power."),
q("PJ",S,"Heat","m","Heat travels through a metal spoon placed in hot tea by:","conduction",["convection","radiation","evaporation"],"Conduction is heat transfer through a solid by particle vibrations."),
q("J",S,"Physics","d","The Sun's heat reaches the Earth mainly by:","radiation",["conduction","convection","evaporation"],"Heat from the Sun travels through empty space as radiation."),
q("PJ",S,"Light","e","Light travels in:","straight lines",["curved lines only","circles","zigzag lines"],"In a uniform medium light travels in straight lines."),
q("PJ",S,"Light","m","The image formed by a plane mirror is:","virtual and laterally inverted",["real and inverted","real and magnified","virtual and upside down"],"A plane mirror gives a virtual, upright, same-size image that is laterally reversed."),
q("J",S,"Light","d","A rainbow is formed by the ___ of sunlight in water droplets.","dispersion",["diffraction only","absorption","polarisation"],"Raindrops refract, reflect and disperse sunlight into its colours."),
q("J",S,"Light","d","A concave lens is used to correct:","short-sightedness",["long-sightedness","colour blindness","cataract"],"Short sight (myopia) is corrected with a diverging (concave) lens."),
q("PJ",S,"Sound","m","Sound cannot travel through:","a vacuum",["water","steel","air"],"Sound needs a material medium."),
q("J",S,"Sound","d","The unit of frequency is the:","hertz",["decibel","metre","newton"],"Frequency is measured in hertz (cycles per second); decibel measures loudness."),
q("PJ",S,"Sound","e","An echo is caused by the ___ of sound.","reflection",["absorption","refraction","dispersion"],"An echo is sound reflected back from a hard surface."),
q("PJ",S,"Electricity","e","Which of these is a good conductor of electricity?","copper",["rubber","wood","plastic"],"Metals such as copper conduct electricity well."),
q("PJ",S,"Electricity","m","The SI unit of electric current is the:","ampere",["volt","ohm","watt"],"Current is measured in amperes."),
q("J",S,"Electricity","m","In a series circuit with two identical bulbs, if one bulb fuses then the other:","goes out",["glows brighter","stays unchanged","glows dimmer"],"A series circuit has a single path, so breaking it anywhere stops the current."),
q("J",S,"Electricity","d","According to Ohm's law, the current through a conductor at constant temperature is proportional to:","the potential difference across it",["its mass","its colour","the time of day"],"V = IR: for a fixed resistance, current is proportional to the voltage."),
q("J",S,"Electricity","d","A 2 ohm resistor carries a current of 3 A. The potential difference across it is:","6 V",["1.5 V","5 V","9 V"],"V = IR = 3 x 2 = 6 V.",chk="6 V"),
# ---- Earth & space, everyday science, general science
q("PJ",S,"Earth and Space","e","Which planet is known as the Red Planet?","Mars",["Venus","Jupiter","Mercury"],"Iron oxide on its surface gives Mars a red colour."),
q("PJ",S,"Earth and Space","e","The Earth takes about ___ to complete one revolution around the Sun.","365 days",["24 hours","30 days","12 months and 6 days"],"One revolution is a year, about 365 and a quarter days."),
q("PJ",S,"Earth and Space","m","A solar eclipse occurs when the:","Moon comes between the Sun and the Earth",["Earth comes between the Sun and the Moon","Sun comes between the Earth and the Moon","Moon is far from the Earth"],"The Moon blocks sunlight from reaching part of the Earth."),
q("J",S,"Earth and Space","m","The largest planet of the solar system is:","Jupiter",["Saturn","Neptune","Earth"],"Jupiter is the largest planet."),
q("J",S,"Earth and Space","d","Seasons on Earth are caused mainly by:","the tilt of the Earth's axis",["the Earth's distance from the Sun","the Moon's gravity","the speed of the Earth's rotation"],"The axial tilt changes how directly sunlight strikes each hemisphere through the year."),
q("P",S,"Earth and Space","e","Which natural satellite orbits the Earth?","Moon",["Phobos","Titan","Europa"],"The Moon is the Earth's only natural satellite."),
q("PJ",S,"Everyday Science","e","Which instrument measures temperature?","thermometer",["barometer","ammeter","speedometer"],"A thermometer measures temperature."),
q("PJ",S,"Everyday Science","m","Which of these is used to measure atmospheric pressure?","barometer",["hygrometer","anemometer","seismograph"],"A barometer measures air pressure."),
q("PJ",S,"Everyday Science","m","The gas used in fire extinguishers is mainly:","carbon dioxide",["oxygen","hydrogen","methane"],"Carbon dioxide displaces oxygen and smothers the flame."),
q("J",S,"Everyday Science","d","Vinegar contains which acid?","acetic acid",["citric acid","sulphuric acid","lactic acid"],"Vinegar is a dilute solution of acetic (ethanoic) acid."),
q("PJ",S,"General Science","e","Which of these is a natural satellite?","Moon",["Sputnik","Hubble telescope","Sun"],"The Moon is natural; Sputnik and Hubble were man-made."),
q("J",S,"General Science","m","The device that converts mechanical energy into electrical energy is a:","generator",["motor","transformer","battery"],"A generator turns mechanical energy into electrical energy; a motor does the reverse."),
q("J",S,"General Science","d","Which of these is a vector quantity?","velocity",["speed","mass","time"],"Velocity has both magnitude and direction."),
q("PJ",S,"General Science","m","Which scientist is known for the law of universal gravitation?","Isaac Newton",["Albert Einstein","Galileo Galilei","Michael Faraday"],"Newton formulated the law of universal gravitation."),
]
