from helpers import q, qf
C = "Social Studies"
rows = [
# ---- Pakistan geography
q("PJ",C,"Pakistan Geography","e","What is the capital of Pakistan?","Islamabad",["Karachi","Lahore","Peshawar"],"Islamabad has been the capital since the 1960s; Karachi was the first capital."),
q("PJ",C,"Pakistan Geography","e","Which is the longest river of Pakistan?","Indus",["Jhelum","Ravi","Chenab"],"The Indus runs the whole length of the country from the north to the Arabian Sea."),
q("P",C,"Pakistan Geography","e","Pakistan's southern coast lies along the:","Arabian Sea",["Red Sea","Bay of Bengal","Caspian Sea"],"The Pakistani coast is on the Arabian Sea."),
q("PJ",C,"Pakistan Geography","m","Which is the second highest mountain in the world, located in Pakistan?","K2",["Nanga Parbat","Tirich Mir","Broad Peak"],"K2 (8,611 m) is the second highest mountain in the world."),
q("PJ",C,"Pakistan Geography","m","Which pass connects Pakistan with Afghanistan near Peshawar?","Khyber Pass",["Bolan Pass","Khunjerab Pass","Lowari Pass"],"The Khyber Pass links Peshawar with Kabul's side; Khunjerab leads to China."),
q("PJ",C,"Pakistan Geography","m","The Khunjerab Pass connects Pakistan with:","China",["Iran","India","Afghanistan"],"Khunjerab is on the Karakoram Highway at the Pakistan-China border."),
q("J",C,"Geography","m","The Thar Desert lies mainly in which province of Pakistan?","Sindh",["Punjab","Balochistan","Khyber Pakhtunkhwa"],"The Pakistani part of the Thar is in the Tharparkar district of Sindh."),
q("J",C,"Geography","d","Which dam on the River Indus is the largest earth-filled dam in Pakistan?","Tarbela Dam",["Mangla Dam","Warsak Dam","Diamer-Bhasha Dam"],"Tarbela Dam, in Khyber Pakhtunkhwa, is the largest earth-filled dam in the country; Mangla is on the Jhelum."),
q("J",C,"Geography","d","The Karakoram Highway links Pakistan with:","China",["Iran","Turkey","Afghanistan"],"The highway runs from Hasan Abdal to the Khunjerab Pass and onward to Kashgar."),
# ---- Provinces / places
q("PJ",C,"Provinces","e","Which is the largest province of Pakistan by area?","Balochistan",["Punjab","Sindh","Khyber Pakhtunkhwa"],"Balochistan covers nearly 44% of the country."),
q("PJ",C,"Provinces","e","Which province has the largest population?","Punjab",["Sindh","Balochistan","Khyber Pakhtunkhwa"],"Punjab is the most populous province."),
q("P",C,"Provinces","e","Quetta is the capital of:","Balochistan",["Sindh","Punjab","Khyber Pakhtunkhwa"],"Quetta is the capital of Balochistan."),
q("PJ",C,"Provinces","m","Peshawar is the provincial capital of:","Khyber Pakhtunkhwa",["Punjab","Balochistan","Sindh"],"Peshawar is the capital of Khyber Pakhtunkhwa."),
q("PJ",C,"Important Places","e","The Badshahi Mosque is located in:","Lahore",["Karachi","Multan","Islamabad"],"The Mughal emperor Aurangzeb built it in Lahore in 1673."),
q("PJ",C,"Important Places","m","Faisal Mosque is located in:","Islamabad",["Lahore","Karachi","Rawalpindi"],"It is one of the largest mosques in the world, in Islamabad."),
q("PJ",C,"Important Places","m","The tomb of Quaid-e-Azam Muhammad Ali Jinnah is in:","Karachi",["Lahore","Islamabad","Hyderabad"],"The Mazar-e-Quaid stands in Karachi."),
q("PJ",C,"Important Places","m","The port of Gwadar is in the province of:","Balochistan",["Sindh","Punjab","Khyber Pakhtunkhwa"],"Gwadar is a deep-sea port on the Balochistan coast."),
# ---- Geography of Sindh
q("PJ",C,"Geography of Sindh","e","What is the capital of Sindh?","Karachi",["Hyderabad","Sukkur","Larkana"],"Karachi is the provincial capital and largest city."),
q("PJ",C,"Geography of Sindh","e","The ancient ruins of Mohenjo-daro are located in the district of:","Larkana",["Thatta","Sukkur","Khairpur"],"Mohenjo-daro, a site of the Indus Valley Civilisation, is in Larkana district."),
q("PJ",C,"Geography of Sindh","m","Which river flows through Sindh to the Arabian Sea?","Indus",["Jhelum","Kabul","Chenab"],"The Indus flows through the length of Sindh and reaches the sea near Thatta."),
q("PJ",C,"Geography of Sindh","m","Manchar Lake, the largest freshwater lake in Pakistan, is in the district of:","Jamshoro",["Thatta","Tharparkar","Ghotki"],"Manchar Lake lies near Sehwan in the Jamshoro district (formerly Dadu)."),
q("J",C,"Sindh History and Geography","m","The Sukkur Barrage on the River Indus was completed in:","1932",["1947","1955","1923"],"The Lloyd (Sukkur) Barrage began operating in 1932."),
q("J",C,"Sindh History and Geography","d","Sindh was separated from the Bombay Presidency as a separate province in:","1936",["1947","1926","1940"],"Sindh became a province on 1 April 1936."),
q("J",C,"Sindh History and Geography","d","The Sindh Assembly passed a resolution in favour of Pakistan in March 1943. Who moved it?","G. M. Syed",["Sir Abdullah Haroon","Allah Bux Soomro","Pir Ilahi Bakhsh"],"G. M. Syed moved the resolution in the Sindh Assembly on 3 March 1943."),
q("J",C,"Sindh History and Geography","d","The Battle of Miani (1843), in which the British defeated the Talpur rulers, was led on the British side by:","Sir Charles Napier",["Lord Clive","Robert Warren Hastings","Lord Dalhousie"],"Napier defeated the Talpurs at Miani and annexed Sindh in 1843."),
q("PJ",C,"Geography of Sindh","m","Keenjhar Lake, the main source of Karachi's drinking water, lies in:","Thatta district",["Sukkur district","Dadu district","Tharparkar district"],"Keenjhar (Kalri) Lake is in Thatta district."),
q("PJ",C,"Geography of Sindh","m","Which city of Sindh is known for the shrine of Lal Shahbaz Qalandar?","Sehwan Sharif",["Thatta","Larkana","Badin"],"The shrine of Lal Shahbaz Qalandar is in Sehwan Sharif."),
# ---- National symbols
q("PJ",C,"National Symbols","e","The national flower of Pakistan is:","jasmine",["rose","tulip","sunflower"],"Jasmine (chambeli) is the national flower."),
q("PJ",C,"National Symbols","e","The national animal of Pakistan is the:","markhor",["snow leopard","lion","Indus dolphin"],"The markhor, a wild mountain goat, is the national animal."),
q("P",C,"National Symbols","e","The national language of Pakistan is:","Urdu",["Sindhi","Punjabi","Pashto"],"Urdu is the national language."),
q("PJ",C,"National Symbols","m","The national anthem of Pakistan was written by:","Hafeez Jalandhari",["Allama Iqbal","Faiz Ahmed Faiz","Ahmed Faraz"],"Hafeez Jalandhari wrote the words; Ahmed G. Chagla composed the music."),
q("PJ",C,"National Symbols","m","The white portion of the Pakistani flag represents:","minorities",["Muslims","progress","peace in the world"],"The white strip stands for religious minorities and the green field for the Muslim majority."),
# ---- History / independence movement / personalities
q("PJ",C,"Independence Movement","e","Pakistan came into being on:","14 August 1947",["23 March 1940","14 August 1948","6 September 1965"],"Pakistan became independent on 14 August 1947."),
q("PJ",C,"Independence Movement","e","The Pakistan Resolution was passed at:","Lahore",["Delhi","Dhaka","Karachi"],"It was adopted at Lahore on 23 March 1940."),
q("PJ",C,"Independence Movement","m","The All-India Muslim League was founded in:","1906 at Dhaka",["1885 at Bombay","1930 at Allahabad","1916 at Lucknow"],"The Muslim League was founded in Dhaka on 30 December 1906."),
q("PJ",C,"Independence Movement","m","The Allahabad Address of 1930, which presented the idea of a separate homeland, was delivered by:","Allama Muhammad Iqbal",["Quaid-e-Azam Jinnah","Chaudhry Rahmat Ali","Sir Syed Ahmad Khan"],"Iqbal presided over the Muslim League session at Allahabad in 1930."),
q("J",C,"Pakistan History","m","The name 'Pakistan' was first coined by:","Chaudhry Rahmat Ali",["Allama Iqbal","Liaquat Ali Khan","Sir Syed Ahmad Khan"],"Chaudhry Rahmat Ali used the name in the 1933 pamphlet 'Now or Never'."),
q("J",C,"Pakistan History","d","The Objectives Resolution, which became a preamble to the constitutions, was passed in:","1949",["1947","1956","1973"],"The Constituent Assembly passed it in March 1949."),
q("J",C,"Pakistan History","d","Pakistan became an Islamic Republic with its first constitution in:","1956",["1947","1962","1973"],"The 1956 constitution made Pakistan an Islamic Republic on 23 March 1956."),
q("J",C,"Pakistan History","d","The Lucknow Pact (1916) was an agreement between the:","Muslim League and the Indian National Congress",["Muslim League and the British government","Congress and the British government","Khilafat Committee and Congress only"],"Jinnah helped to secure the pact giving Muslims separate electorates."),
q("PJ",C,"Important Personalities","e","Who is known as the founder of Pakistan?","Quaid-e-Azam Muhammad Ali Jinnah",["Allama Iqbal","Liaquat Ali Khan","Sir Syed Ahmad Khan"],"Jinnah led the Pakistan Movement and became the first Governor-General."),
q("PJ",C,"Important Personalities","e","The first Prime Minister of Pakistan was:","Liaquat Ali Khan",["Khawaja Nazimuddin","Muhammad Ali Bogra","H. S. Suhrawardy"],"Liaquat Ali Khan served from 1947 until his assassination in 1951."),
q("PJ",C,"Important Personalities","m","The national poet of Pakistan is:","Allama Muhammad Iqbal",["Mirza Ghalib","Altaf Hussain Hali","Hafeez Jalandhari"],"Iqbal is called the poet of the East and the national poet."),
q("PJ",C,"Important Personalities","m","Shah Abdul Latif Bhittai's famous collection of poetry is called:","Shah Jo Risalo",["Bang-e-Dara","Diwan-e-Ghalib","Kulliyat-e-Bedil"],"The Risalo is the masterpiece of the Sindhi Sufi poet."),
q("PJ",C,"Important Personalities","m","Who founded the Aligarh movement and the MAO College?","Sir Syed Ahmad Khan",["Maulana Muhammad Ali Jauhar","Nawab Salimullah","Hakim Ajmal Khan"],"Sir Syed founded the Muhammadan Anglo-Oriental College at Aligarh in 1875."),
q("J",C,"Important Personalities","d","Who was the first Governor-General of Pakistan?","Quaid-e-Azam Muhammad Ali Jinnah",["Khawaja Nazimuddin","Ghulam Muhammad","Iskander Mirza"],"Jinnah took the oath on 15 August 1947."),
q("J",C,"Important Personalities","d","The founder of the Sindhi poetry style of the 'Sur' and a Sufi saint buried at Bhit Shah is:","Shah Abdul Latif Bhittai",["Sachal Sarmast","Shah Inayat","Sami"],"Shah Latif's shrine is at Bhit Shah in Matiari district."),
# ---- Constitution / civics / culture / economy
q("PJ",C,"Constitution and Civics","e","The head of state of Pakistan is the:","President",["Prime Minister","Chief Justice","Army Chief"],"The President is head of state; the Prime Minister heads the government."),
q("PJ",C,"Constitution and Civics","m","The Constitution of Pakistan currently in force was adopted in:","1973",["1956","1962","1947"],"The 1973 Constitution is the present constitution."),
q("PJ",C,"Constitution and Civics","m","The minimum voting age in Pakistan is:","18 years",["21 years","16 years","25 years"],"Citizens aged 18 and above can vote."),
q("J",C,"Civics","m","The highest court of Pakistan's judicial system (apart from specialised federal bodies) is the:","Supreme Court",["High Court","District Court","Sessions Court"],"The Supreme Court is the apex court in the ordinary judicial hierarchy."),
q("J",C,"Constitution","d","Parliament (Majlis-e-Shoora) of Pakistan consists of the President and:","the National Assembly and the Senate",["the National Assembly only","the Senate only","the provincial assemblies"],"The Constitution defines Parliament as the President, the National Assembly and the Senate."),
q("PJ",C,"Culture","e","Which cloth with block-printed patterns is associated with the culture of Sindh?","Ajrak",["Khaddar","Chiffon","Denim"],"Ajrak is a traditional block-printed shawl of Sindh."),
q("PJ",C,"Culture","m","Sindhi Cultural Day is celebrated on:","the first Sunday of December",["14 August","1 January","the first Sunday of March"],"Sindhi Culture Day is observed on the first Sunday of December."),
q("J",C,"Culture","m","The famous folk romance 'Sassui Punhun' belongs to the literature of:","Sindh",["Punjab","Balochistan","Kashmir"],"Sassui Punhun is one of the seven tragic romances in Shah Latif's Risalo."),
q("J",C,"Economy Basics","m","The central bank of Pakistan is the:","State Bank of Pakistan",["National Bank of Pakistan","Habib Bank","Pakistan Stock Exchange"],"The State Bank of Pakistan began operations in July 1948."),
q("J",C,"Economy Basics","d","Which is Pakistan's most important cash crop and a base of its textile industry?","cotton",["sugarcane","tobacco","maize"],"Cotton feeds Pakistan's large textile and clothing sector."),
q("J",C,"Economy Basics","d","The fiscal (financial) year of Pakistan runs from:","1 July to 30 June",["1 January to 31 December","1 April to 31 March","1 October to 30 September"],"The federal budget covers July to June."),
q("J",C,"National Events","m","Which date is observed as Pakistan Day?","23 March",["14 August","6 September","25 December"],"Pakistan Day marks the 1940 Lahore Resolution (and the 1956 constitution)."),
q("J",C,"National Events","d","Youm-e-Takbeer (28 May) commemorates:","Pakistan's nuclear tests of 1998",["the 1965 war","the Lahore Resolution","the first constitution"],"On 28 May 1998 Pakistan conducted nuclear tests in the Chagai hills."),
]
